/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AppState {
  constructor(baseUrl: string, storageDir: string)
  authLogin(email: string, password: string): Promise<string>
  authLogout(): Promise<void>
  authRefreshToken(): Promise<string>
  authFetchOrganizations(): Promise<string>
  authIsAuthenticated(): boolean
  authRestoreSession(): boolean
  authSwitchOrg(slug: string): void
  authGetToken(): string | null
  authGetCurrentUserJson(): string | null
  authGetCurrentOrgJson(): string | null
  authGetOrganizationsJson(): string
  agentListAgents(): Promise<string>
  agentGetConfigSchema(agentSlug: string): Promise<string>
  agentListUserConfigs(): Promise<string>
  agentGetUserConfig(agentSlug: string): Promise<string>
  agentSetUserConfig(agentSlug: string, json: string): Promise<string>
  agentDeleteUserConfig(agentSlug: string): Promise<void>
  agentGetAgentpodSettings(): Promise<string>
  agentUpdateAgentpodSettings(json: string): Promise<string>
  agentListProviders(): Promise<string>
  agentCreateProvider(json: string): Promise<string>
  agentUpdateProvider(id: number, json: string): Promise<string>
  agentDeleteProvider(id: number): Promise<void>
  agentSetDefaultProvider(id: number): Promise<void>
  apikeyList(): Promise<string>
  apikeyGet(id: number): Promise<string>
  apikeyCreate(json: string): Promise<string>
  apikeyUpdate(id: number, json: string): Promise<string>
  apikeyDelete(id: number): Promise<void>
  apikeyRevoke(id: number): Promise<void>
  authApiRegister(json: string): Promise<string>
  authApiVerifyEmail(token: string): Promise<string>
  authApiResendVerification(email: string): Promise<string>
  authApiForgotPassword(email: string): Promise<string>
  authApiResetPassword(json: string): Promise<string>
  autopilotControllersJson(): Promise<string>
  autopilotCurrentControllerJson(): Promise<string>
  autopilotGetControllerByPodKeyJson(podKey: string): Promise<string>
  autopilotGetIterationsJson(key: string): Promise<string>
  autopilotGetThinkingJson(key: string): Promise<string>
  autopilotGetThinkingHistoryJson(key: string): Promise<string>
  autopilotSetControllers(json: string): Promise<void>
  autopilotSetCurrentController(json: string): Promise<void>
  autopilotAddController(json: string): Promise<void>
  autopilotUpdateController(key: string, json: string): Promise<void>
  autopilotRemoveController(key: string): Promise<void>
  autopilotSetIterations(key: string, json: string): Promise<void>
  autopilotAddIteration(key: string, json: string): Promise<void>
  autopilotUpdateThinking(key: string, json: string): Promise<void>
  autopilotFetchControllers(): Promise<string>
  autopilotFetchController(key: string): Promise<string>
  autopilotCreateController(requestJson: string): Promise<string>
  autopilotPauseController(key: string): Promise<void>
  autopilotResumeController(key: string): Promise<void>
  autopilotStopController(key: string): Promise<void>
  autopilotApproveController(key: string, requestJson: string): Promise<void>
  autopilotTakeoverController(key: string): Promise<void>
  autopilotHandbackController(key: string): Promise<void>
  autopilotFetchIterations(key: string): Promise<string>
  billingGetOverview(): Promise<string>
  billingGetSubscription(): Promise<string>
  billingCreateSubscription(json: string): Promise<string>
  billingCancelSubscription(): Promise<string>
  billingUpdateSubscription(json: string): Promise<string>
  billingListPlans(): Promise<string>
  billingGetUsage(usageType?: string | undefined | null): Promise<string>
  billingCheckQuota(resource: string, amount?: number | undefined | null): Promise<string>
  billingCreateCheckout(json: string): Promise<string>
  billingGetCheckoutStatus(orderNo: string): Promise<string>
  billingRequestCancel(json: string): Promise<string>
  billingReactivate(): Promise<string>
  billingUpgrade(json: string): Promise<string>
  billingChangeCycle(json: string): Promise<string>
  billingUpdateAutoRenew(json: string): Promise<string>
  billingGetSeatUsage(): Promise<string>
  billingPurchaseSeats(json: string): Promise<string>
  billingListInvoices(limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  billingGetCustomerPortal(json: string): Promise<string>
  billingGetDeploymentInfo(): Promise<string>
  billingGetPublicPricing(): Promise<string>
  billingGetPublicDeploymentInfo(): Promise<string>
  bindingRequestBinding(json: string, podKey?: string | undefined | null): Promise<string>
  bindingAcceptBinding(json: string): Promise<string>
  bindingRejectBinding(json: string): Promise<void>
  bindingRequestScopes(bindingId: number, json: string): Promise<string>
  bindingApproveScopes(bindingId: number, json: string): Promise<string>
  bindingUnbind(json: string): Promise<void>
  bindingListBindings(status?: string | undefined | null): Promise<string>
  bindingGetPendingBindings(): Promise<string>
  bindingGetBoundPods(): Promise<string>
  bindingCheckBinding(targetPod: string): Promise<string>
  channelChannelsJson(): Promise<string>
  channelCurrentChannelJson(): Promise<string>
  channelGetChannelJson(id: number): Promise<string>
  channelFilterChannelsJson(query: string, includeArchived: boolean): Promise<string>
  channelGetMessagesJson(channelId: number): Promise<string>
  channelGetUnreadCount(channelId: number): Promise<number>
  channelTotalUnreadCount(): Promise<number>
  channelUnreadCountsJson(): Promise<string>
  channelGetMentionCount(channelId: number): Promise<number>
  channelTotalMentionCount(): Promise<number>
  channelMentionCountsJson(): Promise<string>
  channelSortedChannelIdsJson(mode: string, includeArchived: boolean): Promise<string>
  channelGetLastMessageJson(channelId: number): Promise<string>
  channelSetChannels(json: string): Promise<void>
  channelSetCurrentChannel(id?: number | undefined | null): Promise<void>
  channelSelectChannel(id?: number | undefined | null): Promise<string>
  channelAddChannelLocal(json: string): Promise<void>
  channelUpdateChannelLocal(id: number, json: string): Promise<void>
  channelRemoveChannelLocal(id: number): Promise<void>
  channelFetchChannels(includeArchived?: boolean | undefined | null): Promise<string>
  channelFetchChannel(id: number): Promise<string>
  channelCreateChannel(requestJson: string): Promise<string>
  channelUpdateChannel(id: number, requestJson: string): Promise<string>
  channelArchiveChannel(id: number): Promise<void>
  channelUnarchiveChannel(id: number): Promise<void>
  channelJoinChannel(channelId: number, podKey: string): Promise<string>
  channelLeaveChannel(channelId: number, podKey: string): Promise<string>
  channelFetchMessages(channelId: number, limit?: number | undefined | null, beforeId?: number | undefined | null): Promise<string>
  channelSendMessage(channelId: number, requestJson: string): Promise<string>
  channelEditMessage(channelId: number, messageId: number, content: string): Promise<string>
  channelDeleteMessage(channelId: number, messageId: number): Promise<void>
  channelFetchUnreadCounts(): Promise<string>
  channelMarkRead(channelId: number, messageId: number): Promise<void>
  channelMuteChannel(channelId: number, muted: boolean): Promise<void>
  channelGetChannelPods(id: number): Promise<string>
  channelSetCurrentUser(userJson: string): Promise<void>
  channelSetCurrentUserId(userId?: number | undefined | null): Promise<void>
  channelSetMessages(channelId: number, json: string, hasMore: boolean): Promise<void>
  channelPrependMessages(channelId: number, json: string, hasMore: boolean): Promise<void>
  channelAddMessage(channelId: number, json: string): Promise<void>
  channelOnNewMessage(json: string): Promise<boolean>
  channelUpdateMessageLocal(channelId: number, json: string): Promise<void>
  channelRemoveMessageLocal(channelId: number, messageId: number): Promise<void>
  channelSetUnreadCounts(json: string): Promise<void>
  channelIncrementUnread(channelId: number): Promise<void>
  channelClearChannelUnread(channelId: number): Promise<void>
  channelSetMentionCounts(json: string): Promise<void>
  channelIncrementMention(channelId: number): Promise<void>
  channelClearChannelMentions(channelId: number): Promise<void>
  channelSetLastMessage(channelId: number, json: string): Promise<void>
  extensionListSkillRegistries(): Promise<string>
  extensionCreateSkillRegistry(json: string): Promise<string>
  extensionSyncSkillRegistry(id: number): Promise<void>
  extensionToggleSkillRegistry(id: number, json: string): Promise<string>
  extensionDeleteSkillRegistry(id: number): Promise<void>
  extensionListSkillRegistryOverrides(): Promise<string>
  extensionListMarketSkills(query?: string | undefined | null, category?: string | undefined | null): Promise<string>
  extensionListMarketMcpServers(query?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  extensionListRepoSkills(repoId: number, scope?: string | undefined | null): Promise<string>
  extensionInstallSkillFromMarket(repoId: number, json: string): Promise<string>
  extensionInstallSkillFromGithub(repoId: number, json: string): Promise<string>
  extensionUpdateSkill(repoId: number, installId: number, json: string): Promise<string>
  extensionUninstallSkill(repoId: number, installId: number): Promise<void>
  extensionListRepoMcpServers(repoId: number, scope?: string | undefined | null): Promise<string>
  extensionInstallMcpFromMarket(repoId: number, json: string): Promise<string>
  extensionInstallCustomMcpServer(repoId: number, json: string): Promise<string>
  extensionUpdateMcpServer(repoId: number, installId: number, json: string): Promise<string>
  extensionUninstallMcpServer(repoId: number, installId: number): Promise<void>
  extensionInstallSkillFromUpload(repoId: number, fileData: Array<number>, fileName: string, scope?: string | undefined | null): Promise<string>
  filePresignUpload(json: string): Promise<string>
  fileUploadFile(fileData: Array<number>, filename: string, contentType: string): Promise<string>
  invitationList(): Promise<string>
  invitationCreate(json: string): Promise<string>
  invitationRevoke(id: number): Promise<void>
  invitationResend(id: number): Promise<void>
  invitationGetByToken(token: string): Promise<string>
  invitationAccept(token: string): Promise<void>
  invitationListPending(): Promise<string>
  loopSvcLoopsJson(): Promise<string>
  loopSvcCurrentLoopJson(): Promise<string>
  loopSvcRunsJson(): Promise<string>
  loopSvcGetLoopBySlugJson(slug: string): Promise<string>
  loopSvcSetLoops(json: string): Promise<void>
  loopSvcSetCurrentLoop(json: string): Promise<void>
  loopSvcUpdateLoopLocal(slug: string, json: string): Promise<void>
  loopSvcAddRun(json: string): Promise<void>
  loopSvcSetRuns(json: string): Promise<void>
  loopSvcAppendRuns(json: string): Promise<void>
  loopSvcUpdateRunStatus(runId: number, status: string): Promise<void>
  loopSvcClearRuns(): Promise<void>
  loopSvcFetchLoops(status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  loopSvcFetchLoop(slug: string): Promise<string>
  loopSvcCreateLoop(requestJson: string): Promise<string>
  loopSvcUpdateLoop(slug: string, requestJson: string): Promise<string>
  loopSvcDeleteLoop(slug: string): Promise<void>
  loopSvcEnableLoop(slug: string): Promise<string>
  loopSvcDisableLoop(slug: string): Promise<string>
  loopSvcTriggerLoop(slug: string): Promise<string>
  loopSvcFetchRuns(slug: string, status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  loopSvcCancelRun(slug: string, runId: number): Promise<void>
  meshTopologyJson(): Promise<string>
  meshSelectedNode(): Promise<string>
  meshGetNodeJson(podKey: string): Promise<string>
  meshGetEdgesForNodeJson(podKey: string): Promise<string>
  meshGetChannelsForNodeJson(podKey: string): Promise<string>
  meshGetActiveNodesJson(): Promise<string>
  meshGetNodesByRunnerJson(runnerId: number): Promise<string>
  meshGetRunnerInfoJson(runnerId: number): Promise<string>
  meshSetTopology(json: string): Promise<void>
  meshClearTopology(): Promise<void>
  meshSelectNode(podKey?: string | undefined | null): Promise<void>
  meshFetchTopology(): Promise<string>
  messageSendMessage(json: string, podKey?: string | undefined | null): Promise<string>
  messageGetMessages(unreadOnly?: boolean | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  messageGetUnreadCount(): Promise<string>
  messageGetMessage(id: number): Promise<string>
  messageMarkRead(json: string): Promise<void>
  messageMarkAllRead(): Promise<void>
  messageGetConversation(correlationId: string, limit?: number | undefined | null): Promise<string>
  messageGetSentMessages(limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  messageGetDeadLetters(limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  messageReplayDeadLetter(entryId: number): Promise<void>
  notificationGetPreferences(): Promise<string>
  notificationSetPreference(json: string): Promise<string>
  orgList(): Promise<string>
  orgGet(slug: string): Promise<string>
  orgCreate(json: string): Promise<string>
  orgUpdate(slug: string, json: string): Promise<string>
  orgDelete(slug: string): Promise<void>
  orgListMembers(slug: string): Promise<string>
  orgInviteMember(slug: string, json: string): Promise<string>
  orgRemoveMember(slug: string, userId: number): Promise<void>
  orgUpdateMemberRole(slug: string, userId: number, json: string): Promise<string>
  podPodsJson(): Promise<string>
  podCurrentPodJson(): Promise<string>
  podGetPodJson(podKey: string): Promise<string>
  podUpsertPod(podJson: string, timestamp?: number | undefined | null): Promise<void>
  podSetPods(podsJson: string): Promise<void>
  podSetCurrentPod(podJson: string): Promise<void>
  podUpdatePodStatus(podKey: string, status: string, agentStatus?: string | undefined | null, errorCode?: string | undefined | null, errorMessage?: string | undefined | null, timestamp?: number | undefined | null): Promise<void>
  podUpdatePodTitle(podKey: string, title: string, timestamp?: number | undefined | null): Promise<void>
  podUpdatePodAlias(podKey: string, alias: string): Promise<void>
  podUpdateAgentStatus(podKey: string, agentStatus: string): Promise<void>
  podRemovePod(podKey: string): Promise<void>
  podFetchPods(status?: string | undefined | null, runnerId?: number | undefined | null, createdById?: number | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  podFetchSidebarPods(filter: string, userId?: number | undefined | null): Promise<string>
  podLoadMorePods(filter: string, userId: number | undefined | null, offset: number): Promise<string>
  podFetchPod(podKey: string): Promise<string>
  podCreatePod(requestJson: string): Promise<string>
  podTerminatePod(podKey: string): Promise<void>
  podUpdatePodAliasApi(podKey: string, alias?: string | undefined | null): Promise<void>
  podGetPodConnection(podKey: string): Promise<string>
  repositoryList(): Promise<string>
  repositoryGet(id: number): Promise<string>
  repositoryCreate(json: string): Promise<string>
  repositoryUpdate(id: number, json: string): Promise<string>
  repositoryDelete(id: number): Promise<void>
  repositoryListBranches(id: number): Promise<string>
  repositorySyncBranches(id: number, json: string): Promise<string>
  repositoryRegisterWebhook(id: number): Promise<void>
  repositoryDeleteWebhook(id: number): Promise<void>
  repositoryGetWebhookStatus(id: number): Promise<string>
  repositoryGetWebhookSecret(id: number): Promise<string>
  repositoryListMergeRequests(id: number, branch?: string | undefined | null, mrState?: string | undefined | null): Promise<string>
  repositoryMarkWebhookConfigured(id: number): Promise<void>
  runnerRunnersJson(): Promise<string>
  runnerAvailableRunnersJson(): Promise<string>
  runnerCurrentRunnerJson(): Promise<string>
  runnerGetRunnerJson(id: number): Promise<string>
  runnerSetRunners(json: string): Promise<void>
  runnerSetAvailableRunners(json: string): Promise<void>
  runnerSetCurrentRunner(json: string): Promise<void>
  runnerUpdateRunnerLocal(id: number, json: string): Promise<void>
  runnerUpdateRunnerStatus(id: number, status: string): Promise<void>
  runnerRemoveRunnerLocal(id: number): Promise<void>
  runnerFetchRunners(status?: string | undefined | null): Promise<string>
  runnerFetchAvailableRunners(): Promise<string>
  runnerFetchRunner(id: number): Promise<string>
  runnerUpdateRunner(id: number, requestJson: string): Promise<string>
  runnerDeleteRunner(id: number): Promise<void>
  runnerCreateToken(requestJson: string): Promise<string>
  runnerFetchTokens(): Promise<string>
  runnerDeleteToken(id: number): Promise<void>
  runnerListRunnerLogs(id: number): Promise<string>
  runnerRequestLogUpload(id: number): Promise<void>
  runnerUpgradeRunner(id: number, requestJson: string): Promise<string>
  runnerListRunnerPods(id: number, status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  runnerQueryRunnerSandboxes(id: number, requestJson: string): Promise<string>
  runnerGetAuthStatus(authKey: string): Promise<string>
  runnerAuthorizeRunner(requestJson: string): Promise<string>
  supportTicketList(status?: string | undefined | null, page?: number | undefined | null, pageSize?: number | undefined | null): Promise<string>
  supportTicketGetDetail(id: number): Promise<string>
  supportTicketGetAttachmentUrl(id: number): Promise<string>
  supportTicketCreateTicket(title: string, category: string, content: string, priority: string | undefined | null, fileData: Array<Array<number>>, fileNames: Array<string>): Promise<string>
  supportTicketAddMessage(ticketId: number, content: string, fileData: Array<Array<number>>, fileNames: Array<string>): Promise<string>
  ticketTicketsJson(): Promise<string>
  ticketGetTicketBySlugJson(slug: string): Promise<string>
  ticketCurrentTicketJson(): Promise<string>
  ticketBoardColumnsJson(): Promise<string>
  ticketLabelsJson(): Promise<string>
  ticketFilterTicketsJson(search: string, statusesJson: string, prioritiesJson: string, repositoryIdsJson: string): Promise<string>
  ticketSetTickets(json: string): Promise<void>
  ticketAddTicket(json: string): Promise<void>
  ticketUpdateTicketLocal(slug: string, json: string): Promise<void>
  ticketUpdateTicketStatusLocal(slug: string, status: string): Promise<void>
  ticketRemoveTicket(slug: string): Promise<void>
  ticketSetCurrentTicket(json: string): Promise<void>
  ticketSetBoardColumns(json: string): Promise<void>
  ticketAppendColumnTickets(status: string, json: string): Promise<void>
  ticketSetLabels(json: string): Promise<void>
  ticketAddLabel(json: string): Promise<void>
  ticketRemoveLabel(id: number): Promise<void>
  ticketFetchTickets(status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  ticketFetchBoard(repositoryId?: number | undefined | null): Promise<string>
  ticketLoadMoreColumn(status: string, offset: number, limit: number): Promise<string>
  ticketFetchTicket(slug: string): Promise<string>
  ticketCreateTicket(requestJson: string): Promise<string>
  ticketUpdateTicket(slug: string, requestJson: string): Promise<string>
  ticketDeleteTicket(slug: string): Promise<void>
  ticketUpdateTicketStatus(slug: string, status: string): Promise<string>
  ticketFetchLabels(repositoryId?: number | undefined | null): Promise<string>
  ticketCreateLabel(name: string, color: string, repositoryId?: number | undefined | null): Promise<string>
  ticketDeleteLabel(id: number): Promise<void>
  ticketGetTicketPods(slug: string, activeOnly?: boolean | undefined | null): Promise<string>
  ticketGetSubTickets(slug: string): Promise<string>
  ticketRelationsListRelations(slug: string): Promise<string>
  ticketRelationsCreateRelation(slug: string, json: string): Promise<string>
  ticketRelationsDeleteRelation(slug: string, relationId: number): Promise<void>
  ticketRelationsListCommits(slug: string): Promise<string>
  ticketRelationsLinkCommit(slug: string, json: string): Promise<string>
  ticketRelationsUnlinkCommit(slug: string, commitId: number): Promise<void>
  ticketRelationsListMergeRequests(slug: string): Promise<string>
  ticketRelationsListComments(slug: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  ticketRelationsCreateComment(slug: string, json: string): Promise<string>
  ticketRelationsUpdateComment(slug: string, commentId: number, json: string): Promise<string>
  ticketRelationsDeleteComment(slug: string, commentId: number): Promise<void>
  userGetMe(): Promise<string>
  userGetOrganizations(): Promise<string>
  userCredentialListGitCredentials(): Promise<string>
  userCredentialCreateGitCredential(json: string): Promise<string>
  userCredentialGetGitCredential(id: number): Promise<string>
  userCredentialUpdateGitCredential(id: number, json: string): Promise<string>
  userCredentialDeleteGitCredential(id: number): Promise<void>
  userCredentialGetDefaultGitCredential(): Promise<string>
  userCredentialSetDefaultGitCredential(json: string): Promise<void>
  userCredentialClearDefaultGitCredential(): Promise<void>
  userCredentialListAgentCredentials(): Promise<string>
  userCredentialListAgentCredentialsForAgent(agentSlug: string): Promise<string>
  userCredentialCreateAgentCredential(agentSlug: string, json: string): Promise<string>
  userCredentialGetAgentCredential(id: number): Promise<string>
  userCredentialUpdateAgentCredential(id: number, json: string): Promise<string>
  userCredentialDeleteAgentCredential(id: number): Promise<void>
  userCredentialSetDefaultAgentCredential(id: number): Promise<void>
  userCredentialListRepoProviders(): Promise<string>
  userCredentialCreateRepoProvider(json: string): Promise<string>
  userCredentialGetRepoProvider(id: number): Promise<string>
  userCredentialUpdateRepoProvider(id: number, json: string): Promise<string>
  userCredentialDeleteRepoProvider(id: number): Promise<void>
  userCredentialSetDefaultRepoProvider(id: number): Promise<void>
  userCredentialTestRepoProvider(id: number): Promise<void>
  userCredentialListProviderRepositories(id: number, page?: number | undefined | null, perPage?: number | undefined | null, search?: string | undefined | null): Promise<string>
  tokenUsageGetDashboard(startTime?: string | undefined | null, endTime?: string | undefined | null, agentSlug?: string | undefined | null, userId?: number | undefined | null, model?: string | undefined | null, granularity?: string | undefined | null): Promise<string>
}
