version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /runner
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /relay
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /clients/web
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /clients/web-admin
    schedule:
      interval: weekly
