packages:
  - clients/web
  - clients/web-admin
  - clients/desktop
  - packages/*
  - clients/core/crates/node-bridge
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - electron
  - esbuild
  - "@parcel/watcher"
