// Ambient declaration for the Bazel-built Rust → wasm-bindgen npm package.
// The real .d.ts is generated by `//clients/core/crates/wasm:wasm_pkg`
// and consumed via `//:node_modules/agentsmesh-wasm` at bazel build time.
// Raw tsc / IDE sessions don't see that mount — this stub names the
// wasm-bindgen classes used at type-position so IntelliSense resolves
// (the bazel build remains the SSOT for actual type correctness).
declare module "agentsmesh-wasm" {
  export default function initWasm(): Promise<void>;

  // wasm-bindgen-decorated Rust structs surfaced as opaque classes here.
  // Method signatures are intentionally permissive — the bazel build
  // resolves the real generated .d.ts; this stub only names them.
  // The intersection with `[key: string]: any` covers static methods
  // (e.g. WasmWebSocket.connect) that the bazel-generated .d.ts exposes.
  type WasmClass = (new (...args: any[]) => { [key: string]: any }) & {
    [key: string]: any;
  };
  export const WasmApiClient: WasmClass;
  export const WasmAuthManager: WasmClass;
  export const WasmEventsManager: WasmClass;
  export const WasmWebSocket: WasmClass;
  export const WasmPodService: WasmClass;
  export const WasmPodState: WasmClass;
  export const WasmTicketService: WasmClass;
  export const WasmTicketState: WasmClass;
  export const WasmTicketRelationsService: WasmClass;
  export const WasmChannelService: WasmClass;
  export const WasmChannelState: WasmClass;
  export const WasmRunnerService: WasmClass;
  export const WasmRunnerState: WasmClass;
  export const WasmLoopService: WasmClass;
  export const WasmLoopState: WasmClass;
  export const WasmAutopilotService: WasmClass;
  export const WasmAutopilotState: WasmClass;
  export const WasmMeshService: WasmClass;
  export const WasmMeshState: WasmClass;
  export const WasmBillingService: WasmClass;
  export const WasmRepositoryService: WasmClass;
  export const WasmRepoState: WasmClass;
  export const WasmExtensionService: WasmClass;
  export const WasmInvitationService: WasmClass;
  export const WasmApiKeyService: WasmClass;
  export const WasmGrantService: WasmClass;
  export const WasmBindingService: WasmClass;
  export const WasmNotificationService: WasmClass;
  export const WasmPromoCodeService: WasmClass;
  export const WasmTokenUsageService: WasmClass;
  export const WasmSSOService: WasmClass;
  export const WasmUserApiService: WasmClass;
  export const WasmUserCredentialService: WasmClass;
  export const WasmEnvBundleService: WasmClass;
  export const WasmOrgApiService: WasmClass;
  export const WasmAgentService: WasmClass;
  export const WasmFileService: WasmClass;
  export const WasmSupportTicketService: WasmClass;
  export const WasmAuthConnectService: WasmClass;
  export const WasmBlockstoreService: WasmClass;
  export const WasmAcpSessionManager: WasmClass;
  export const WasmRelayManager: WasmClass;

  // Re-export as types so `import type { WasmFoo }` works at type position.
  export type WasmApiClient = InstanceType<typeof WasmApiClient>;
  export type WasmAuthManager = InstanceType<typeof WasmAuthManager>;
  export type WasmEventsManager = InstanceType<typeof WasmEventsManager>;
  export type WasmWebSocket = InstanceType<typeof WasmWebSocket>;
  export type WasmPodService = InstanceType<typeof WasmPodService>;
  export type WasmPodState = InstanceType<typeof WasmPodState>;
  export type WasmTicketService = InstanceType<typeof WasmTicketService>;
  export type WasmTicketState = InstanceType<typeof WasmTicketState>;
  export type WasmTicketRelationsService = InstanceType<typeof WasmTicketRelationsService>;
  export type WasmChannelService = InstanceType<typeof WasmChannelService>;
  export type WasmChannelState = InstanceType<typeof WasmChannelState>;
  export type WasmRunnerService = InstanceType<typeof WasmRunnerService>;
  export type WasmRunnerState = InstanceType<typeof WasmRunnerState>;
  export type WasmLoopService = InstanceType<typeof WasmLoopService>;
  export type WasmLoopState = InstanceType<typeof WasmLoopState>;
  export type WasmAutopilotService = InstanceType<typeof WasmAutopilotService>;
  export type WasmAutopilotState = InstanceType<typeof WasmAutopilotState>;
  export type WasmMeshService = InstanceType<typeof WasmMeshService>;
  export type WasmMeshState = InstanceType<typeof WasmMeshState>;
  export type WasmBillingService = InstanceType<typeof WasmBillingService>;
  export type WasmRepositoryService = InstanceType<typeof WasmRepositoryService>;
  export type WasmRepoState = InstanceType<typeof WasmRepoState>;
  export type WasmExtensionService = InstanceType<typeof WasmExtensionService>;
  export type WasmInvitationService = InstanceType<typeof WasmInvitationService>;
  export type WasmApiKeyService = InstanceType<typeof WasmApiKeyService>;
  export type WasmGrantService = InstanceType<typeof WasmGrantService>;
  export type WasmBindingService = InstanceType<typeof WasmBindingService>;
  export type WasmNotificationService = InstanceType<typeof WasmNotificationService>;
  export type WasmPromoCodeService = InstanceType<typeof WasmPromoCodeService>;
  export type WasmTokenUsageService = InstanceType<typeof WasmTokenUsageService>;
  export type WasmSSOService = InstanceType<typeof WasmSSOService>;
  export type WasmUserApiService = InstanceType<typeof WasmUserApiService>;
  export type WasmUserCredentialService = InstanceType<typeof WasmUserCredentialService>;
  export type WasmEnvBundleService = InstanceType<typeof WasmEnvBundleService>;
  export type WasmOrgApiService = InstanceType<typeof WasmOrgApiService>;
  export type WasmAgentService = InstanceType<typeof WasmAgentService>;
  export type WasmFileService = InstanceType<typeof WasmFileService>;
  export type WasmSupportTicketService = InstanceType<typeof WasmSupportTicketService>;
  export type WasmAuthConnectService = InstanceType<typeof WasmAuthConnectService>;
  export type WasmBlockstoreService = InstanceType<typeof WasmBlockstoreService>;
  export type WasmAcpSessionManager = InstanceType<typeof WasmAcpSessionManager>;
  export type WasmRelayManager = InstanceType<typeof WasmRelayManager>;

  export function version(): string;
  export function init_logger(level?: string): void;
  export function log_event(level?: string, target?: string, msg?: string): void;

  export function relay_encode_input(...args: any[]): Uint8Array;
  export function relay_decode_message(
    data: Uint8Array,
  ): { type: number; payload: Uint8Array } | null;
  export function relay_encode_resize(...args: any[]): Uint8Array;
  export function relay_encode_ping(...args: any[]): Uint8Array;
  export function relay_encode_control(...args: any[]): Uint8Array;
  export function relay_encode_resync(...args: any[]): Uint8Array;
  export function relay_encode_acp_command(...args: any[]): Uint8Array;
}
