#!/bin/bash
# =============================================================================
# AgentsMesh 开发环境一键初始化脚本
# =============================================================================
#
# 一键启动完整的开发环境，包括：
#   1. 生成 worktree 隔离的 .env 配置
#   2. 启动后端 Docker 服务（前端在本地运行）
#   3. 执行数据库迁移
#   4. 初始化 seed 数据
#   5. 启动本地前端（Web + Admin Console）
#
# 使用方法：
#   ./dev.sh         # 一键启动开发环境
#   ./dev.sh --clean # 清理并重建（失败时使用）
#
# 本地前端开发：
#   cd web && pnpm dev --turbopack
#
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
MIGRATIONS_DIR="$SCRIPT_DIR/../../backend/migrations"
SEED_FILE="$SCRIPT_DIR/seed/seed.sql"
LEMONSQUEEZY_SEED_FILE="$SCRIPT_DIR/seed/seed_lemonsqueezy.sql"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; }

# 获取 worktree 名称
get_worktree_name() {
    local git_dir
    git_dir=$(git rev-parse --git-dir 2>/dev/null)

    if [[ "$git_dir" == *".git/worktrees/"* ]]; then
        # worktree 的 git-dir 格式: /path/to/repo/.git/worktrees/<worktree-name>
        basename "$git_dir"
    else
        git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main"
    fi | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]'
}

# 计算端口偏移量
# 使用 6 位哈希，范围 1-500，降低冲突概率
calculate_port_offset() {
    local name="$1"
    if [[ "$name" == "main" || "$name" == "master" ]]; then
        echo 0
    else
        local hash
        if command -v md5sum &>/dev/null; then
            hash=$(echo -n "$name" | md5sum | cut -c1-6)
        else
            hash=$(echo -n "$name" | md5 | cut -c1-6)
        fi
        echo $(( (16#$hash % 500) + 1 ))
    fi
}

# 生成 SSL 证书 (gRPC + mTLS)
generate_ssl_certs() {
    local ssl_dir="$SCRIPT_DIR/ssl"
    if [ -f "$ssl_dir/ca.crt" ] && [ -f "$ssl_dir/ca.key" ]; then
        info "SSL 证书已存在"
        return 0
    fi

    info "生成 SSL 证书 (gRPC + mTLS)..."
    "$SCRIPT_DIR/generate-dev-certs.sh" > /dev/null 2>&1
    success "SSL 证书生成完成"
}

# 生成 AI CLI 配置文件
generate_ai_cli_configs() {
    local config_dir="$SCRIPT_DIR/ai-cli-configs"

    # Claude Code settings
    mkdir -p "$config_dir/claude"
    cat > "$config_dir/claude/settings.json" << 'EOF'
{
  "permissions": {
    "allow": [
      "Bash",
      "Read",
      "Write",
      "Edit",
      "Glob",
      "Grep"
    ],
    "deny": []
  },
  "api_key_helper": null
}
EOF

    # Codex CLI config (Rust version >= 0.100.0)
    mkdir -p "$config_dir/codex"
    cat > "$config_dir/codex/config.toml" << 'EOF'
# Codex CLI configuration for headless mode
# Reference: https://developers.openai.com/codex/config-reference/

# Approval policy: "on-request", "never", "untrusted"
approval_policy = "never"

# Sandbox mode: "read-only", "workspace-write", "danger-full-access"
sandbox_mode = "workspace-write"
EOF

    # Gemini CLI settings
    mkdir -p "$config_dir/gemini"
    cat > "$config_dir/gemini/settings.json" << 'EOF'
{
  "sandboxMode": "none",
  "autoApprove": true
}
EOF

    success "生成 AI CLI 配置"
}

# 生成 Traefik 配置（动态设置网络名 + host-side service 端口）
generate_traefik_config() {
    local worktree_name="${WORKTREE_NAME:-main}"
    local project_name="agentsmesh-${worktree_name}"
    local traefik_yml="$SCRIPT_DIR/traefik/traefik.yml"
    local dynamic_dir="$SCRIPT_DIR/traefik/dynamic"
    mkdir -p "$dynamic_dir"

    cat > "$traefik_yml" << EOF
# Traefik Static Configuration for Development
# Auto-generated by dev.sh - project: $project_name
#
# After the air → ibazel switch, backend / runner / relay run on the
# developer host (not in docker). Traefik discovers them via the file
# provider only — docker provider was removed because no relevant
# services are in the compose network anymore.

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  grpc:
    address: ":9443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: DEBUG
  format: common

accessLog:
  format: common
EOF

    # Dynamic HTTP routing — points at host backend / relay through
    # host.docker.internal. Ports come from .env (worktree-scoped).
    cat > "$dynamic_dir/http.yml" << EOF
# HTTP routing — Auto-generated by dev.sh
# host services listen on worktree-scoped ports; traefik proxies in
# from :HTTP_PORT and forwards via host.docker.internal.

http:
  routers:
    backend-api:
      entryPoints:
        - web
      rule: "PathPrefix(\`/api\`) || PathPrefix(\`/health\`)"
      service: backend-api
      priority: 100

    relay:
      entryPoints:
        - web
      rule: "PathPrefix(\`/relay\`)"
      service: relay
      middlewares:
        - relay-strip
      priority: 30

  middlewares:
    relay-strip:
      stripPrefix:
        prefixes:
          - "/relay"

  services:
    backend-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${BACKEND_HTTP_PORT}"

    relay:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${RELAY_HTTP_PORT}"
EOF

    # Dynamic gRPC mTLS passthrough → host backend
    cat > "$dynamic_dir/grpc.yml" << EOF
# gRPC mTLS passthrough — Auto-generated by dev.sh
# Backend handles mTLS verification; traefik just tunnels TCP+TLS.

tcp:
  routers:
    grpc-mtls:
      entryPoints:
        - grpc
      rule: "HostSNI(\`*\`)"
      service: backend-grpc
      tls:
        passthrough: true

  services:
    backend-grpc:
      loadBalancer:
        servers:
          - address: "host.docker.internal:${BACKEND_GRPC_PORT}"
EOF
    success "生成 Traefik 配置 (host backend=:${BACKEND_HTTP_PORT} grpc=:${BACKEND_GRPC_PORT} relay=:${RELAY_HTTP_PORT})"
}

# =============================================================================
# Host-side service helpers (Bazel ibazel mode — replaces docker air)
# =============================================================================

# All host-side runtime state lives under deploy/dev/runtime/ (gitignored).
# Each service has its own pid file + log file. Runner gets an isolated
# HOME so its `~/.claude.json` etc. don't pollute the developer's real
# config. Workspaces / certs also live here per-worktree.
_runtime_dir() { echo "$SCRIPT_DIR/runtime"; }

check_ibazel_doctor() {
    local missing=()
    command -v bazel >/dev/null 2>&1 || missing+=("bazel (bazelisk)")
    if (( ${#missing[@]} > 0 )); then
        error "缺少必需工具：${missing[*]}"
        echo "  macOS: brew install bazelisk"
        echo "  Linux: 见 https://github.com/bazelbuild/bazelisk/releases"
        exit 1
    fi

    # ibazel is *recommended* (provides hot reload) but not mandatory.
    # CI runs dev.sh without ibazel and falls back to one-shot `bazel run`
    # in `_launch_ibazel` (see HAS_IBAZEL detection there).
    if ! command -v ibazel >/dev/null 2>&1; then
        warn "ibazel 未安装，host service 将退化为单次 bazel run（无 hot reload）"
        echo "  macOS: brew install bazel-watcher"
        echo "  Linux: 见 https://github.com/bazelbuild/bazel-watcher/releases"
    fi

    # AI CLI tools are required by the runner. Warn (don't fail) so
    # backend / relay can still come up for non-pod work.
    local ai_missing=()
    command -v claude >/dev/null 2>&1 || ai_missing+=("claude")
    command -v codex >/dev/null 2>&1 || ai_missing+=("codex")
    command -v gemini >/dev/null 2>&1 || ai_missing+=("gemini")
    if (( ${#ai_missing[@]} > 0 )); then
        warn "AI CLI 未全装（${ai_missing[*]}）— runner pod 创建会受限"
        echo "  npm i -g @anthropic-ai/claude-code @openai/codex @google/gemini-cli"
    fi
}

# Generate runner mTLS client cert (replaces runner-entrypoint.sh logic).
# Cert lives under runtime/runner/certs/ — re-generated only if missing.
# NOTE: kept as a host-side helper for tools that need to inspect the
# cert from outside the runner container, but the runner container has
# its own copy (mounted via runner-entrypoint.sh). Not called from
# main() anymore.
generate_runner_cert() {
    local rt_dir="$(_runtime_dir)/runner"
    local certs_dir="$rt_dir/certs"
    local ssl_dir="$SCRIPT_DIR/ssl"
    local node_id="${RUNNER_NODE_ID:-dev-runner}"
    local org_slug="${RUNNER_ORG_SLUG:-dev-org}"

    mkdir -p "$certs_dir"

    if [[ -f "$certs_dir/runner.crt" && -f "$certs_dir/runner.key" ]]; then
        return 0
    fi
    if [[ ! -f "$ssl_dir/ca.crt" || ! -f "$ssl_dir/ca.key" ]]; then
        error "CA 证书未找到: $ssl_dir (先跑 generate_ssl_certs)"
        return 1
    fi

    info "生成 Runner mTLS 客户端证书..."
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:prime256v1 \
        -out "$certs_dir/runner.key" 2>/dev/null
    openssl req -new -key "$certs_dir/runner.key" \
        -out "$certs_dir/runner.csr" \
        -subj "/CN=${node_id}/O=${org_slug}/OU=Runner" 2>/dev/null
    cat > "$certs_dir/runner_ext.cnf" << 'EOF'
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
EOF
    openssl x509 -req -days 365 \
        -in "$certs_dir/runner.csr" \
        -CA "$ssl_dir/ca.crt" -CAkey "$ssl_dir/ca.key" \
        -CAserial "$certs_dir/ca.srl" -CAcreateserial \
        -out "$certs_dir/runner.crt" \
        -extfile "$certs_dir/runner_ext.cnf" 2>/dev/null
    cp "$ssl_dir/ca.crt" "$certs_dir/ca.crt"
    rm -f "$certs_dir/runner.csr" "$certs_dir/runner_ext.cnf"
    chmod 600 "$certs_dir/runner.key"
    chmod 644 "$certs_dir/runner.crt" "$certs_dir/ca.crt"
    success "Runner 证书生成完成 ($certs_dir)"
}

# Build the runner binary via Bazel (linux/amd64 cross-compile).
# Output: bazel-bin/runner/cmd/runner/runner_/runner. We then copy it
# to deploy/dev/runner-binary so the docker build context (which is
# `deploy/dev`) can reach it — bazel-bin is a symlink to /private/var/...
# that docker build cannot follow across.
build_runner_binary() {
    info "Bazel build runner binary (linux/amd64)..."
    local repo_root="$SCRIPT_DIR/../.."
    (
        cd "$repo_root"
        bazel build //runner/cmd/runner:runner \
            --platforms=@rules_go//go/toolchain:linux_amd64
    ) || {
        error "bazel build runner 失败"
        return 1
    }
    # `cp -L` dereferences the bazel-bin symlink chain to copy the
    # actual ELF binary into the docker build context. Remove first
    # because bazel outputs are read-only and a previous copy will
    # block overwrite.
    rm -f "$SCRIPT_DIR/runner-binary"
    cp -L "$repo_root/bazel-bin/runner/cmd/runner/runner_/runner" \
        "$SCRIPT_DIR/runner-binary"
    chmod +x "$SCRIPT_DIR/runner-binary"
    success "Runner binary 已编译并复制到 build context"
}


# Wait for an HTTP endpoint to return success.
_wait_http() {
    local url="$1" name="$2" max="${3:-40}"
    for ((i=1; i<=max; i++)); do
        if curl -sf "$url" >/dev/null 2>&1; then return 0; fi
        sleep 1
    done
    error "$name 健康检查超时 ($url)"
    return 1
}

# Background-launch a service. Uses ibazel (hot reload) when installed;
# falls back to plain `bazel run` for CI / minimal-tooling environments.
# Args: name target [extra args...]. Writes pid + log under runtime/<name>/.
_launch_ibazel() {
    local name="$1" target="$2"; shift 2
    local rt_dir="$(_runtime_dir)/$name"
    mkdir -p "$rt_dir"
    local pid_file="$rt_dir/$name.pid"
    local log_file="$rt_dir/$name.log"

    # Reap any orphan from a previous run.
    if [[ -f "$pid_file" ]]; then
        local old=$(cat "$pid_file")
        if kill -0 "$old" 2>/dev/null; then
            kill -TERM "$old" 2>/dev/null || true
            sleep 1
        fi
        rm -f "$pid_file"
    fi

    local launcher
    if command -v ibazel >/dev/null 2>&1; then
        launcher="ibazel"
    else
        launcher="bazel"
    fi
    info "启动 host service: $name (target: $target, launcher: $launcher)"
    local repo_root="$SCRIPT_DIR/../.."
    (
        cd "$repo_root"
        nohup $launcher run "$target" "$@" > "$log_file" 2>&1 &
        echo $! > "$pid_file"
        disown
    )
}

start_backend_host() {
    source "$ENV_FILE"
    local repo_root="$SCRIPT_DIR/../.."

    # Ensure logs dir exists for backend's LOG_FILE.
    mkdir -p "$repo_root/backend/logs"

    # Backend env — same as the docker compose backend service had,
    # but DB / redis / minio go through host port forwards.
    export DB_HOST=localhost
    export DB_PORT="$POSTGRES_PORT"
    export DB_USER=agentsmesh
    export DB_PASSWORD="${POSTGRES_PASSWORD:-agentsmesh_dev}"
    export DB_NAME=agentsmesh
    export DB_SSLMODE=disable
    export REDIS_URL="redis://localhost:${REDIS_PORT}"
    export JWT_SECRET="${JWT_SECRET:-dev-jwt-secret-change-in-production}"
    export INTERNAL_API_SECRET="${INTERNAL_API_SECRET:-dev-internal-secret}"
    export SERVER_ADDRESS=":${BACKEND_HTTP_PORT}"
    export GRPC_ADDRESS=":${BACKEND_GRPC_PORT}"
    export GRPC_PUBLIC_ENDPOINT="grpcs://127.0.0.1:${GRPC_PORT}"
    export DEBUG=true
    export PRIMARY_DOMAIN="${PRIMARY_DOMAIN}"
    export USE_HTTPS="${USE_HTTPS:-false}"
    export BLOCKSTORE_WEBHOOK_ALLOW_HOSTS="host.docker.internal,host.lan,localhost,127.0.0.1"
    export CORS_ALLOWED_ORIGINS="http://localhost:${HTTP_PORT},http://127.0.0.1:${HTTP_PORT},http://localhost:${WEB_PORT},http://127.0.0.1:${WEB_PORT},http://localhost:${WEB_ADMIN_PORT},http://127.0.0.1:${WEB_ADMIN_PORT}"
    export LOG_LEVEL=debug
    export LOG_FORMAT=text
    export LOG_FILE="$repo_root/backend/logs/agentsmesh.log"
    export EMAIL_PROVIDER=console
    export STORAGE_ENDPOINT="localhost:${MINIO_API_PORT}"
    export STORAGE_PUBLIC_ENDPOINT="localhost:${MINIO_API_PORT}"
    export STORAGE_REGION=us-east-1
    export STORAGE_BUCKET=agentsmesh
    export STORAGE_ACCESS_KEY="${MINIO_ROOT_USER:-minioadmin}"
    export STORAGE_SECRET_KEY="${MINIO_ROOT_PASSWORD:-minioadmin}"
    export STORAGE_USE_SSL=false
    export STORAGE_USE_PATH_STYLE=true
    export STORAGE_MAX_FILE_SIZE=10
    export STORAGE_ALLOWED_TYPES="image/jpeg,image/png,image/gif,image/webp,application/pdf"
    export DEPLOYMENT_TYPE="${DEPLOYMENT_TYPE:-global}"
    export PAYMENT_MOCK="${PAYMENT_MOCK:-false}"
    export PKI_CA_CERT_FILE="$SCRIPT_DIR/ssl/ca.crt"
    export PKI_CA_KEY_FILE="$SCRIPT_DIR/ssl/ca.key"
    export PKI_VALIDITY_DAYS=365
    export GEO_MMDB_PATH="${GEO_MMDB_PATH:-}"  # optional
    export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:${OTEL_GRPC_PORT}"
    export OTEL_SERVICE_NAME=agentsmesh-backend
    export OTEL_TRACES_SAMPLER_ARG=1.0

    _launch_ibazel backend //backend/cmd/server:server

    if ! _wait_http "http://localhost:${BACKEND_HTTP_PORT}/health" backend 60; then
        error "Backend 启动失败，查看日志: $(_runtime_dir)/backend/backend.log"
        return 1
    fi
    success "Backend 已就绪 (host :${BACKEND_HTTP_PORT}, gRPC :${BACKEND_GRPC_PORT})"
}

start_relay_host() {
    source "$ENV_FILE"
    # relay reads SERVER_PORT (not SERVER_ADDRESS like backend) — see
    # relay/internal/config/config.go.
    export SERVER_HOST="0.0.0.0"
    export SERVER_PORT="${RELAY_HTTP_PORT}"
    export WS_READ_BUFFER_SIZE=4096
    export WS_WRITE_BUFFER_SIZE=4096
    export JWT_SECRET="${JWT_SECRET:-dev-jwt-secret-change-in-production}"
    export BACKEND_URL="http://localhost:${HTTP_PORT}"
    export INTERNAL_API_SECRET="${INTERNAL_API_SECRET:-dev-internal-secret}"
    export RELAY_ID=dev-relay-1
    export RELAY_REGION=local
    export RELAY_CAPACITY=1000
    export PRIMARY_DOMAIN="${PRIMARY_DOMAIN}"
    export USE_HTTPS="${USE_HTTPS:-false}"
    export SESSION_KEEP_ALIVE_DURATION=30s
    export DEBUG=true
    export OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:${OTEL_GRPC_PORT}"
    export OTEL_SERVICE_NAME=agentsmesh-relay
    export OTEL_TRACES_SAMPLER_ARG=1.0

    _launch_ibazel relay //relay/cmd/relay:relay

    if ! _wait_http "http://localhost:${RELAY_HTTP_PORT}/health" relay 30; then
        error "Relay 启动失败，查看日志: $(_runtime_dir)/relay/relay.log"
        return 1
    fi
    success "Relay 已就绪 (host :${RELAY_HTTP_PORT})"
}


stop_host_services() {
    local rt_root="$(_runtime_dir)"
    [[ -d "$rt_root" ]] || return 0
    # Runner stays in docker now — only backend / relay run as host
    # ibazel processes.
    for svc in backend relay; do
        local pid_file="$rt_root/$svc/$svc.pid"
        if [[ -f "$pid_file" ]]; then
            local pid
            pid=$(cat "$pid_file")
            if kill -0 "$pid" 2>/dev/null; then
                info "停止 host $svc (pid: $pid)..."
                # ibazel spawns child processes; use process group kill.
                kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
                pkill -P "$pid" 2>/dev/null || true
            fi
            rm -f "$pid_file"
        fi
    done
    pkill -f 'ibazel run //backend/cmd/server' 2>/dev/null || true
    pkill -f 'ibazel run //relay/cmd/relay' 2>/dev/null || true
    # Plain `bazel run` fallback (CI mode without ibazel).
    pkill -f 'bazel run //backend/cmd/server' 2>/dev/null || true
    pkill -f 'bazel run //relay/cmd/relay' 2>/dev/null || true
}


# 生成 .env 配置
generate_env() {
    local worktree_name=$(get_worktree_name)
    local project_name="agentsmesh-${worktree_name}"

    # If .env already exists for this project, preserve existing ports to keep
    # runner configs, stored endpoints, and other tools stable across runs.
    if [[ -f "$ENV_FILE" ]] && grep -q "COMPOSE_PROJECT_NAME=$project_name" "$ENV_FILE"; then
        source "$ENV_FILE"
        WORKTREE_NAME="$worktree_name"
        PORT_OFFSET=$(( (HTTP_PORT - 10000) / 50 ))
        # Backfill WEB_ADMIN_PORT for .env files created before this field existed
        if ! grep -q "WEB_ADMIN_PORT" "$ENV_FILE"; then
            local admin_port=$((10011 + PORT_OFFSET * 50))
            echo "WEB_ADMIN_PORT=$admin_port" >> "$ENV_FILE"
            export WEB_ADMIN_PORT="$admin_port"
            info "补充 WEB_ADMIN_PORT=$admin_port 到 .env"
        fi
        # Backfill host-side service ports (added with the air → ibazel switch).
        # Slots 15/16/17 in the 50-step worktree window.
        if ! grep -q "BACKEND_HTTP_PORT" "$ENV_FILE"; then
            local backend_http=$((10015 + PORT_OFFSET * 50))
            local backend_grpc=$((10016 + PORT_OFFSET * 50))
            local relay_http=$((10017 + PORT_OFFSET * 50))
            {
                echo ""
                echo "# Host-side service ports (Bazel ibazel mode — see dev.sh start_*_host)"
                echo "BACKEND_HTTP_PORT=$backend_http"
                echo "BACKEND_GRPC_PORT=$backend_grpc"
                echo "RELAY_HTTP_PORT=$relay_http"
            } >> "$ENV_FILE"
            export BACKEND_HTTP_PORT="$backend_http"
            export BACKEND_GRPC_PORT="$backend_grpc"
            export RELAY_HTTP_PORT="$relay_http"
            info "补充 host service 端口: backend=$backend_http grpc=$backend_grpc relay=$relay_http"
        fi
        success "保留现有端口配置 (worktree: $worktree_name, PRIMARY_DOMAIN: localhost:$HTTP_PORT)"
        return 0
    fi

    local offset=$(calculate_port_offset "$worktree_name")

    # 保存到全局变量供其他函数使用
    WORKTREE_NAME="$worktree_name"
    PORT_OFFSET="$offset"

    # 计算端口
    local http_port=$((10000 + offset * 50))
    local grpc_port=$((10001 + offset * 50))

    cat > "$ENV_FILE" << EOF
# AgentsMesh Dev Environment - Auto-generated
# Worktree: $worktree_name | Offset: $offset

COMPOSE_PROJECT_NAME=$project_name

# =============================================================================
# Unified Domain Configuration - Single Source of Truth
# All URLs (OAuth callbacks, webhooks, Relay, etc.) are derived from this
# =============================================================================
PRIMARY_DOMAIN=localhost:$http_port
USE_HTTPS=false

# =============================================================================
# Ports (步长 50，支持最多 500 个 worktree，端口范围 10000-35000)
# Slots 0-14: external (docker-exposed) ports
# Slots 15-17: host-side ibazel service ports (loopback only, behind traefik)
# =============================================================================
HTTP_PORT=$http_port
GRPC_PORT=$grpc_port
POSTGRES_PORT=$((10002 + offset * 50))
REDIS_PORT=$((10003 + offset * 50))
MINIO_API_PORT=$((10004 + offset * 50))
MINIO_CONSOLE_PORT=$((10005 + offset * 50))
ADMINER_PORT=$((10006 + offset * 50))
WEB_PORT=$((10007 + offset * 50))
TRAEFIK_DASHBOARD_PORT=$((10008 + offset * 50))
GITEA_HTTP_PORT=$((10009 + offset * 50))
GITEA_SSH_PORT=$((10010 + offset * 50))
WEB_ADMIN_PORT=$((10011 + offset * 50))
OTEL_GRPC_PORT=$((10012 + offset * 50))
OTEL_HTTP_PORT=$((10013 + offset * 50))
JAEGER_UI_PORT=$((10014 + offset * 50))

# Host-side service ports (Bazel ibazel mode — see dev.sh start_*_host)
BACKEND_HTTP_PORT=$((10015 + offset * 50))
BACKEND_GRPC_PORT=$((10016 + offset * 50))
RELAY_HTTP_PORT=$((10017 + offset * 50))

# =============================================================================
# Credentials
# =============================================================================
POSTGRES_PASSWORD=agentsmesh_dev
JWT_SECRET=dev-jwt-secret-change-in-production
INTERNAL_API_SECRET=dev-internal-secret
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin

# =============================================================================
# OAuth (optional) - Only ClientID/Secret needed, RedirectURLs derived
# =============================================================================
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# =============================================================================
# AI CLI - Claude Code
# =============================================================================
ANTHROPIC_BASE_URL=https://api.anthropic.com
ANTHROPIC_AUTH_TOKEN=
EOF
    success "生成 .env 配置 (worktree: $worktree_name, PRIMARY_DOMAIN: localhost:$http_port)"
}

# 生成 clients/web/.env.local 配置（支持本地前端开发）
generate_web_env() {
    local offset="${PORT_OFFSET:-0}"
    local worktree_name="${WORKTREE_NAME:-main}"
    local http_port=$((10000 + offset * 50))
    local web_env_file="$SCRIPT_DIR/../../clients/web/.env.local"

    cat > "$web_env_file" << EOF
# Auto-generated by dev.sh
# Worktree: $worktree_name | HTTP Port: $http_port
#
# Unified Domain Configuration - 所有 URL 从 PRIMARY_DOMAIN 派生
# 变量名与 Backend/Relay 完全统一

# =============================================================================
# Unified Domain Configuration - Single Source of Truth
# =============================================================================
PRIMARY_DOMAIN=localhost:$http_port
USE_HTTPS=false

# =============================================================================
# 本地开发特殊配置
# =============================================================================
# 前端 API 基础 URL（留空使用相对路径，由 Next.js rewrites 代理）
NEXT_PUBLIC_API_URL=

# WebSocket URL（直连后端，Next.js rewrites 不支持 WebSocket 代理）
NEXT_PUBLIC_WS_URL=ws://127.0.0.1:$http_port

# Next.js rewrites 代理目标（仅服务端使用，不暴露给浏览器）
# 使用 127.0.0.1 而非 localhost，避免 IPv6 解析问题（Docker 端口映射只绑定 IPv4）
API_PROXY_TARGET=http://127.0.0.1:$http_port

# OAuth (optional)
NEXT_PUBLIC_GITHUB_CLIENT_ID=
EOF
    success "生成 clients/web/.env.local (PRIMARY_DOMAIN: localhost:$http_port)"
}

# 生成 clients/web-admin/.env.local 配置（支持本地 Admin Console 开发）
generate_web_admin_env() {
    local offset="${PORT_OFFSET:-0}"
    local worktree_name="${WORKTREE_NAME:-main}"
    local http_port=$((10000 + offset * 50))
    local web_admin_env_file="$SCRIPT_DIR/../../clients/web-admin/.env.local"

    cat > "$web_admin_env_file" << EOF
# Auto-generated by dev.sh
# Worktree: $worktree_name | HTTP Port: $http_port
#
# Unified Domain Configuration - Admin Console

# =============================================================================
# Unified Domain Configuration - Single Source of Truth
# =============================================================================
PRIMARY_DOMAIN=localhost:$http_port
USE_HTTPS=false
EOF
    success "生成 clients/web-admin/.env.local (PRIMARY_DOMAIN: localhost:$http_port)"
}

# 等待服务就绪
wait_for_service() {
    local container="$1"
    local check_cmd="$2"
    local max_retries=30

    for ((i=1; i<=max_retries; i++)); do
        if docker exec "$container" $check_cmd &>/dev/null; then
            return 0
        fi
        sleep 2
    done
    return 1
}

# 执行数据库迁移
run_migrations() {
    # Migrations run via the `migrate` oneshot service (docker-compose
    # `profiles: [tools]`). The migrate container shares postgres's
    # network so we can target localhost:5432 inside the container.
    local db_url="postgres://agentsmesh:agentsmesh_dev@localhost:5432/agentsmesh?sslmode=disable"
    local compose_run="docker compose run --rm --no-deps migrate"

    info "执行数据库迁移 (docker oneshot migrate)..."

    # Check current version first; surface dirty state explicitly.
    local migration_output
    migration_output=$($compose_run -database "$db_url" version 2>&1) || true
    if echo "$migration_output" | grep -q "dirty"; then
        warn "检测到迁移状态为 dirty，尝试修复..."
        local dirty_version
        dirty_version=$(echo "$migration_output" | grep -oE '[0-9]+' | head -1)
        if [[ -n "$dirty_version" ]]; then
            $compose_run -database "$db_url" force "$dirty_version" >/dev/null 2>&1 || true
            success "已修复 dirty 状态 (version: $dirty_version)"
        fi
    fi

    local migrate_result
    migrate_result=$($compose_run -database "$db_url" up 2>&1) || true

    # Match "no change" or "^error" — same logic as before, just hosted
    # by the migrate image instead of execed into the backend container.
    if echo "$migrate_result" | grep -q "no change"; then
        info "数据库已是最新版本"
    elif echo "$migrate_result" | grep -q "^error"; then
        error "迁移失败:"
        echo "$migrate_result" | sed 's/^/    /'
        local current_version latest_version
        current_version=$($compose_run -database "$db_url" version 2>&1 | grep -oE '^[0-9]+' || echo "0")
        latest_version=$(ls -1 "$MIGRATIONS_DIR"/*.up.sql 2>/dev/null | \
            sed 's/.*\/\([0-9]*\)_.*/\1/' | sort -n | tail -1)

        if [[ -n "$latest_version" && "$current_version" != "0" && "$current_version" != "$latest_version" ]]; then
            warn "已有部分迁移应用 (version=$current_version)，强制设置到 $latest_version"
            $compose_run -database "$db_url" force "$latest_version" >/dev/null 2>&1 || true
        else
            error "Fresh database — refusing to force version. Fix the migration and rerun."
            return 1
        fi
    else
        success "数据库迁移完成"
    fi

    local final_version
    final_version=$($compose_run -database "$db_url" version 2>&1 | head -1)
    info "当前迁移版本: $final_version"
}

# 初始化 seed 数据
init_seed() {
    local pg_container="$1"

    # 检查是否已有 seed 数据
    local user_exists
    user_exists=$(docker exec "$pg_container" psql -U agentsmesh -d agentsmesh -t -c \
        "SELECT COUNT(*) FROM users WHERE email = 'dev@agentsmesh.local'" 2>/dev/null | tr -d ' ')

    if [[ "$user_exists" -gt 0 ]]; then
        info "Seed 数据已存在，跳过"
        return 0
    fi

    info "初始化 seed 数据..."
    docker exec -i "$pg_container" psql -U agentsmesh -d agentsmesh < "$SEED_FILE" &>/dev/null

    # 应用 LemonSqueezy Variant IDs 配置
    if [[ -f "$LEMONSQUEEZY_SEED_FILE" ]]; then
        info "配置 LemonSqueezy Variant IDs..."
        docker exec -i "$pg_container" psql -U agentsmesh -d agentsmesh < "$LEMONSQUEEZY_SEED_FILE" &>/dev/null
    fi

    success "Seed 数据初始化完成"
}

# 初始化 Gitea Git 服务器
init_gitea() {
    local gitea_container="${COMPOSE_PROJECT_NAME}-gitea-1"
    source "$ENV_FILE"
    local gitea_port="${GITEA_HTTP_PORT:-3001}"

    # Wait for Gitea healthcheck
    info "等待 Gitea 就绪..."
    local max_retries=30
    for ((i=1; i<=max_retries; i++)); do
        if curl -s "http://localhost:${gitea_port}/api/v1/version" &>/dev/null; then
            break
        fi
        if [[ $i -eq $max_retries ]]; then
            warn "Gitea 启动超时，跳过初始化"
            return 0
        fi
        sleep 2
    done
    success "Gitea 已就绪"

    # Run init script
    "$SCRIPT_DIR/gitea/init-gitea.sh" "$gitea_container" "$gitea_port"
}

# Generate the runner SSH keypair used to access Gitea repos.
# The private key is never committed; if it's missing (first clone, new machine),
# generate a fresh pair. init_gitea will register the new public key with Gitea.
#
# Also validates existing key pairs: if id_ed25519 and id_ed25519.pub are
# mismatched (e.g., one was regenerated without the other), SSH will refuse to
# authenticate with "identity_sign: private key contents do not match public".
# We detect this and regenerate both files to fix it automatically.
generate_runner_ssh_key() {
    local ssh_dir="$SCRIPT_DIR/runner-ssh"
    local private_key="$ssh_dir/id_ed25519"
    local public_key="$ssh_dir/id_ed25519.pub"

    if [[ -f "$private_key" ]]; then
        # Validate that the key pair is consistent.
        # OpenSSH will reject the key with a cryptic "contents do not match
        # public" error if the .pub file is stale or missing.
        local needs_regen=false

        if [[ ! -f "$public_key" ]]; then
            warn "Public key missing, will regenerate SSH key pair"
            needs_regen=true
        else
            # Derive the public key from the private key and compare with .pub file.
            # Only compare key type + key data (fields 1-2), ignoring the comment.
            local derived_key stored_key
            derived_key=$(ssh-keygen -y -f "$private_key" 2>/dev/null | awk '{print $1, $2}')
            stored_key=$(awk '{print $1, $2}' "$public_key" 2>/dev/null)

            if [[ -z "$derived_key" || "$derived_key" != "$stored_key" ]]; then
                warn "SSH key pair mismatch detected, will regenerate"
                needs_regen=true
            fi
        fi

        if [[ "$needs_regen" == true ]]; then
            rm -f "$private_key" "$public_key"
        else
            chmod 600 "$private_key"
            info "Runner SSH key already exists and is valid"
            return 0
        fi
    fi

    info "Generating runner SSH key (private key not committed)..."
    ssh-keygen -t ed25519 -C "agentsmesh-dev-runner@local" -f "$private_key" -N "" > /dev/null
    chmod 600 "$private_key"
    success "Runner SSH key generated: $private_key"
}

# Configure ~/.ssh/config so that local runners (running on the host, outside Docker)
# can clone git@gitea:org/repo.git URLs. Inside Docker, "gitea" resolves via Docker DNS.
# On the host, SSH would fail with "nodename not known" — we fix this by adding a managed
# Host block that maps "gitea" → 127.0.0.1 on the worktree-specific SSH port.
#
# Safe to re-run: removes the old managed block and rewrites it with the current port.
setup_gitea_ssh_config() {
    source "$ENV_FILE"
    local ssh_dir="$HOME/.ssh"
    local ssh_config="$ssh_dir/config"
    local gitea_ssh_port="${GITEA_SSH_PORT:-2222}"
    local identity_file="$SCRIPT_DIR/runner-ssh/id_ed25519"
    local marker_start="# BEGIN AgentsMesh dev gitea"
    local marker_end="# END AgentsMesh dev gitea"

    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
    [[ -f "$ssh_config" ]] || touch "$ssh_config"
    chmod 600 "$ssh_config"

    # Remove any existing managed block so we can re-append with the current port.
    local tmp
    tmp=$(mktemp)
    awk "/^${marker_start}$/,/^${marker_end}$/{next} {print}" "$ssh_config" > "$tmp"
    cat "$tmp" > "$ssh_config"
    rm -f "$tmp"

    cat >> "$ssh_config" << EOF

${marker_start}
Host gitea
    HostName 127.0.0.1
    Port ${gitea_ssh_port}
    IdentityFile ${identity_file}
    IdentitiesOnly yes
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
${marker_end}
EOF

    success "SSH config: git@gitea:... → 127.0.0.1:${gitea_ssh_port} (key: runner-ssh/id_ed25519)"
}

# Kill all stale runner-related processes and restart Docker runner/relay containers.
# Use this when runners are in a bad state and you want a clean slate.
reset_runners() {
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
    fi

    echo ""
    echo "=========================================="
    echo "  Reset Runner (rebuild bazel binary + restart container)"
    echo "=========================================="
    echo ""

    # 1. Optional: kill any externally-installed runner CLI process.
    if pgrep -f "agentsmesh-runner" &>/dev/null; then
        info "停止本地 agentsmesh-runner 进程..."
        pkill -f "agentsmesh-runner" 2>/dev/null || true
        sleep 1
        pkill -9 -f "agentsmesh-runner" 2>/dev/null || true
    fi

    # 2. Rebuild runner binary via Bazel (linux/amd64 cross-compile).
    build_runner_binary || return 1

    # 3. Rebuild + restart the runner container so the new binary is
    #    picked up. `--build` forces a fresh COPY of bazel-bin/.../runner.
    cd "$SCRIPT_DIR"
    info "重建并重启 runner 容器..."
    docker compose up -d --build runner 2>&1 | grep -v "^#" | grep -v warning || true
    success "Runner 容器已重启 (binary 来自 bazel build)"

    echo ""
}

# 清理环境
clean() {
    # 读取端口配置
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
    fi
    local web_port="${WEB_PORT:-3000}"

    local web_admin_port="${WEB_ADMIN_PORT:-3001}"

    # 停止 host-side ibazel services (backend / runner / relay)
    info "停止 host-side ibazel 服务..."
    stop_host_services
    success "host-side 服务已停止"

    # 停止前端进程
    if lsof -i :"$web_port" &>/dev/null; then
        info "停止前端服务 (端口: $web_port)..."
        lsof -ti :"$web_port" | xargs kill -9 2>/dev/null || true
        success "前端服务已停止"
    fi

    # 停止 Admin Console 进程
    if lsof -i :"$web_admin_port" &>/dev/null; then
        info "停止 Admin Console (端口: $web_admin_port)..."
        lsof -ti :"$web_admin_port" | xargs kill -9 2>/dev/null || true
        success "Admin Console 已停止"
    fi

    # 清理前端日志
    rm -f "$SCRIPT_DIR/web.log"
    rm -f "$SCRIPT_DIR/web-admin.log"
    # 清理 host-side 运行时状态 (pid/log/cert/runner workspace + isolated HOME)
    rm -rf "$(_runtime_dir)"

    if [[ -f "$ENV_FILE" ]]; then
        info "清理 Docker 环境: ${COMPOSE_PROJECT_NAME:-agentsmesh}..."
        cd "$SCRIPT_DIR"
        docker compose down -v --remove-orphans 2>/dev/null || true
        rm -f "$ENV_FILE"
        success "清理完成"
    else
        warn "Docker 环境未初始化"
    fi
}

# 显示结果
show_result() {
    source "$ENV_FILE"

    echo ""
    echo "=========================================="
    echo "  AgentsMesh 开发环境已就绪!"
    echo "=========================================="
    echo ""
    echo "  前端:       http://localhost:$WEB_PORT"
    echo "  Admin:      http://localhost:$WEB_ADMIN_PORT"
    echo "  API:        http://localhost:$HTTP_PORT/api  (→ host backend :$BACKEND_HTTP_PORT)"
    echo "  Relay:      ws://localhost:$HTTP_PORT/relay  (→ host relay :$RELAY_HTTP_PORT)"
    echo "  gRPC mTLS:  grpcs://localhost:$GRPC_PORT      (→ host backend :$BACKEND_GRPC_PORT)"
    echo ""
    echo "  Host services (ibazel hot-reload):"
    echo "    backend  日志: tail -f deploy/dev/runtime/backend/backend.log"
    echo "    relay    日志: tail -f deploy/dev/runtime/relay/relay.log"
    echo ""
    echo "  Docker runner (bazel-built binary, no hot reload):"
    echo "    日志: docker compose logs -f runner"
    echo "    重 build: ./dev.sh --rebuild-runner"
    echo ""
    echo "  测试账号:   dev@agentsmesh.local / devpass123"
    echo "  管理员:     admin@agentsmesh.local / adminpass123"
    echo ""
    echo "  其他服务:"
    echo "    Gitea:    http://localhost:$GITEA_HTTP_PORT (gitea-admin / gitea-admin-123)"
    echo "    Traefik:  http://localhost:$TRAEFIK_DASHBOARD_PORT (Dashboard)"
    echo "    Adminer:  http://localhost:$ADMINER_PORT"
    echo "    MinIO:    http://localhost:$MINIO_CONSOLE_PORT"
    echo "    Jaeger:   http://localhost:$JAEGER_UI_PORT (Tracing UI)"
    echo ""
    echo "  停止: ./dev.sh --clean"
    echo "  仅重 build runner: ./dev.sh --rebuild-runner"
    echo ""
}

# 启动本地前端
start_frontend() {
    source "$ENV_FILE"
    local web_dir="$SCRIPT_DIR/../../clients/web"
    local web_port="${WEB_PORT:-3000}"
    local lock_file="$web_dir/.next/dev/lock"
    local stale_lock=false

    # Kill any stale Next.js process holding the lock, then clear it
    if [[ -f "$lock_file" ]]; then
        warn "检测到残留的 Next.js 锁文件，清理中..."
        pkill -f "next dev" 2>/dev/null || true
        # Also kill anything still holding the port (port may outlive the process briefly)
        lsof -ti :"$web_port" 2>/dev/null | xargs kill -9 2>/dev/null || true
        sleep 1
        rm -f "$lock_file"
        rm -rf "$web_dir/.next/cache"
        success "锁文件和缓存已清理"
        stale_lock=true
    fi

    # 检查是否已有前端进程在运行（端口占用）
    # Skip this check if we just cleaned a stale lock — always restart in that case
    if [[ "$stale_lock" == false ]] && lsof -i :"$web_port" &>/dev/null; then
        warn "端口 $web_port 已被占用，跳过前端启动"
        return 0
    fi

    # 检查 bazel + pnpm（Bazel-driven dev workflow，但仍需 pnpm 解析外部依赖）
    if ! command -v bazel &>/dev/null; then
        error "未找到 bazel"
        return 1
    fi
    if ! command -v pnpm &>/dev/null; then
        error "未找到 pnpm，请先安装: npm install -g pnpm"
        return 1
    fi

    # 检查依赖（根目录 lockfile 变化时重新安装）
    local root_dir="$SCRIPT_DIR/../.."
    local lockfile="$root_dir/pnpm-lock.yaml"
    local lockfile_hash_file="$root_dir/node_modules/.pnpm-lock-hash"
    local current_hash=""
    local cached_hash=""
    [[ -f "$lockfile" ]] && current_hash=$(md5 -q "$lockfile" 2>/dev/null || md5sum "$lockfile" | cut -d' ' -f1)
    [[ -f "$lockfile_hash_file" ]] && cached_hash=$(cat "$lockfile_hash_file")

    if [[ ! -d "$root_dir/node_modules" || "$current_hash" != "$cached_hash" ]]; then
        info "安装前端依赖（根 workspace）..."
        (cd "$root_dir" && pnpm install --frozen-lockfile) || {
            error "前端依赖安装失败"
            return 1
        }
        echo "$current_hash" > "$lockfile_hash_file"
        rm -rf "$web_dir/.next/cache"
        success "前端依赖安装完成"
    fi

    # 启动前端（后台运行，日志输出到文件）
    # 走 Bazel 的 next_dev devserver — 这样 @agentsmesh/* 的 internal
    # packages 通过 //:node_modules/@agentsmesh/<name> 链接进 sandbox，
    # Next.js 能正常解析。源码 pnpm node_modules 没有这些链接（pure
    # Bazel 接管 internal packages 之后），不能直接 `next dev`。
    local log_file="$SCRIPT_DIR/web.log"
    info "启动前端服务 (端口: $web_port, Bazel devserver)..."
    local saved_dir="$PWD"
    cd "$root_dir"
    bazel run //clients/web:next_dev -- --port "$web_port" > "$log_file" 2>&1 < /dev/null &
    disown $!
    cd "$saved_dir"

    # 等待前端启动
    local max_wait=60
    for ((i=1; i<=max_wait; i++)); do
        if curl -s "http://localhost:$web_port" &>/dev/null; then
            success "前端服务已启动 (http://localhost:$web_port)"
            return 0
        fi
        sleep 1
    done

    warn "前端服务启动中，请稍后访问 http://localhost:$web_port"
    echo "  查看日志: tail -f $log_file"
}

# 启动本地 Admin Console 前端
start_admin_frontend() {
    source "$ENV_FILE"
    local web_admin_dir="$SCRIPT_DIR/../../clients/web-admin"
    local web_admin_port="${WEB_ADMIN_PORT:-3001}"
    local lock_file="$web_admin_dir/.next/dev/lock"
    local stale_lock=false

    # Kill any stale Next.js process holding the lock, then clear it
    if [[ -f "$lock_file" ]]; then
        warn "检测到残留的 Admin Console 锁文件，清理中..."
        lsof -ti :"$web_admin_port" 2>/dev/null | xargs kill -9 2>/dev/null || true
        sleep 1
        rm -f "$lock_file"
        rm -rf "$web_admin_dir/.next/cache"
        success "Admin Console 锁文件和缓存已清理"
        stale_lock=true
    fi

    # 检查是否已有进程在运行
    if [[ "$stale_lock" == false ]] && lsof -i :"$web_admin_port" &>/dev/null; then
        warn "端口 $web_admin_port 已被占用，跳过 Admin Console 启动"
        return 0
    fi

    # 检查 pnpm
    if ! command -v pnpm &>/dev/null; then
        error "未找到 pnpm，跳过 Admin Console 启动"
        return 0
    fi

    # 检查依赖（根目录 lockfile，web-admin deps 已 hoist 到根）
    local root_dir="$SCRIPT_DIR/../.."
    local lockfile="$root_dir/pnpm-lock.yaml"
    local lockfile_hash_file="$root_dir/node_modules/.pnpm-lock-hash"
    local current_hash="" cached_hash=""
    [[ -f "$lockfile" ]] && current_hash=$(md5 -q "$lockfile" 2>/dev/null || md5sum "$lockfile" | cut -d' ' -f1)
    [[ -f "$lockfile_hash_file" ]] && cached_hash=$(cat "$lockfile_hash_file")

    if [[ ! -d "$root_dir/node_modules" || "$current_hash" != "$cached_hash" ]]; then
        info "安装 Admin Console 依赖（根 workspace）..."
        (cd "$root_dir" && pnpm install --frozen-lockfile) || {
            error "Admin Console 依赖安装失败"
            return 0
        }
        echo "$current_hash" > "$lockfile_hash_file"
        rm -rf "$web_admin_dir/.next/cache"
        success "Admin Console 依赖安装完成"
    fi

    # 启动 Admin Console（后台运行）— 走 Bazel devserver 同 web。
    local log_file="$SCRIPT_DIR/web-admin.log"
    info "启动 Admin Console (端口: $web_admin_port, Bazel devserver)..."
    local saved_dir="$PWD"
    cd "$root_dir"
    bazel run //clients/web-admin:next_dev -- --port "$web_admin_port" > "$log_file" 2>&1 < /dev/null &
    disown $!
    cd "$saved_dir"

    # 等待启动
    local max_wait=60
    for ((i=1; i<=max_wait; i++)); do
        if curl -s "http://localhost:$web_admin_port" &>/dev/null; then
            success "Admin Console 已启动 (http://localhost:$web_admin_port)"
            return 0
        fi
        sleep 1
    done

    warn "Admin Console 启动中，请稍后访问 http://localhost:$web_admin_port"
    echo "  查看日志: tail -f $log_file"
}


# 主流程
main() {
    cd "$SCRIPT_DIR"

    # 处理 --clean 参数
    if [[ "${1:-}" == "--clean" || "${1:-}" == "-c" ]]; then
        clean
        exit 0
    fi

    # 处理 --reset-runners 参数
    if [[ "${1:-}" == "--reset-runners" || "${1:-}" == "--kill-runners" || "${1:-}" == "--rebuild-runner" ]]; then
        reset_runners
        exit 0
    fi

    # `--backend-only`: skip frontend startup (Web + Web-Admin). For CI
    # e2e jobs that bring up the docker stack here and start the Web
    # dev-server separately under Bazel.
    local backend_only=false
    if [[ "${1:-}" == "--backend-only" ]]; then
        backend_only=true
    fi

    # 显示帮助
    if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
        echo "用法: $0 [选项]"
        echo ""
        echo "选项:"
        echo "  无参数             一键启动完整开发环境"
        echo "                       - docker: postgres/redis/minio/traefik/runner 等基础设施"
        echo "                       - host:   backend / relay / web / web-admin (ibazel + next dev)"
        echo "  --backend-only     仅启动 docker 基础设施 + host backend/relay (CI 用)"
        echo "  --rebuild-runner   重 build runner binary (bazel) + 重启 runner 容器"
        echo "  --clean            停止并清理所有服务"
        echo ""
        echo "  改动 backend / relay 源码: ibazel 自动重 build (host)"
        echo "  改动 runner 源码:        ./dev.sh --rebuild-runner"
        echo ""
        echo "前端日志: tail -f deploy/dev/web.log"
        exit 0
    fi

    echo ""
    echo "=========================================="
    echo "  AgentsMesh 开发环境初始化"
    echo "=========================================="
    echo ""

    # Step 1: 生成 SSL 证书
    generate_ssl_certs

    # Step 2: 生成 AI CLI 配置（保留：CI / 工具脚本仍可能引用 deploy/dev/ai-cli-configs/）
    generate_ai_cli_configs

    # Step 3: 生成配置
    generate_env
    source "$ENV_FILE"

    # Step 3.5: ibazel doctor — 早失败比起容器起来后报错更友好
    check_ibazel_doctor

    # Step 4: 生成 Traefik 配置（动态网络名 + host 端口）
    generate_traefik_config

    # Step 5: 生成 clients/web/.env.local（支持本地前端开发）
    generate_web_env

    # Step 5.5: 生成 clients/web-admin/.env.local（支持本地 Admin Console 开发）
    generate_web_admin_env

    # Step 5.8: Generate runner SSH key pair (host runner 也需要它做 git 操作)
    generate_runner_ssh_key

    # Step 5.9: Build runner binary via Bazel (linux/amd64). Required
    # before docker compose up — runner.Dockerfile COPYs the binary
    # from bazel-bin/ into the dev image.
    build_runner_binary

    # Step 6: 启动 Docker 基础设施 + runner (postgres / redis / minio / traefik / jaeger / gitea / otelcol / adminer / runner)
    info "启动 Docker 基础设施 + runner (首次可能需要几分钟)..."
    local up_attempt=0
    local up_max=3
    while [ $up_attempt -lt $up_max ]; do
        up_attempt=$((up_attempt + 1))
        if docker compose up -d --build --quiet-pull 2>&1 | grep -v "^#" | grep -v "^\[" | grep -v "^$"; then
            break
        fi
        if [ $up_attempt -eq $up_max ]; then
            error "Docker compose up failed after $up_max attempts"
            exit 1
        fi
        warn "compose up failed (attempt $up_attempt/$up_max) — retrying in 10s"
        sleep 10
    done
    success "Docker 基础设施已启动"

    # Step 7: 等待 PostgreSQL
    local pg_container="${COMPOSE_PROJECT_NAME}-postgres-1"
    info "等待 PostgreSQL 就绪..."
    if ! wait_for_service "$pg_container" "pg_isready -U agentsmesh"; then
        error "PostgreSQL 启动超时"
        exit 1
    fi
    success "PostgreSQL 已就绪"

    # Step 8: 执行迁移 (docker compose run --rm migrate — backend 不在 docker 跑了)
    run_migrations

    # Step 9: 初始化 seed
    init_seed "$pg_container"

    # Step 9.5: 初始化 Gitea Git 服务器 (SSH key already generated at Step 5.8)
    init_gitea

    # Step 9.6: Configure local SSH so git@gitea:... works outside Docker
    setup_gitea_ssh_config

    # Step 10: 启动 host-side backend + relay via ibazel.
    # backend 必须先起 — runner 容器通过 traefik:9443 (mTLS gRPC) 连
    # backend，traefik passthrough 到 host backend。
    start_backend_host
    start_relay_host

    # Step 11: 启动本地前端
    if [[ "$backend_only" == "true" ]]; then
        info "--backend-only: skipping frontend startup"
    else
        start_frontend

        # Step 11.5: 启动本地 Admin Console
        start_admin_frontend
    fi

    # 显示结果
    show_result
}

main "$@"
