/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AppState {
  constructor(baseUrl: string, storageDir: string)
  apiGet(endpoint: string): Promise<string>
  apiPost(endpoint: string, body: string): Promise<string>
  apiPut(endpoint: string, body: string): Promise<string>
  apiPatch(endpoint: string, body: string): Promise<string>
  apiDelete(endpoint: string): Promise<string>
  apiOrgPath(path: string): string
  authLogin(email: string, password: string): Promise<string>
  authLogout(): Promise<void>
  authRefreshToken(): Promise<string>
  authFetchOrganizations(): Promise<string>
  authIsAuthenticated(): boolean
  authRestoreSession(): boolean
  authSwitchOrg(slug: string): void
  authGetToken(): string | null
  authGetCurrentUserJson(): string | null
  authGetCurrentOrgJson(): string | null
  authGetOrganizationsJson(): string
  authApplySession(sessionJson: string): void
  authSetOrganizations(orgsJson: string): void
  authSetCurrentOrg(orgJson: string): void
  authClearSession(): void
  authLoginProto(email: string, password: string): Promise<Array<number>>
  authRefreshTokenProto(): Promise<Array<number>>
  authFetchOrganizationsProto(): Promise<Array<number>>
  authBootstrapProto(): Promise<Array<number>>
  authGetCurrentUserProto(): Array<number> | null
  agentGetAgentpodSettings(): Promise<string>
  agentUpdateAgentpodSettings(json: string): Promise<string>
  agentListProviders(): Promise<string>
  agentCreateProvider(json: string): Promise<string>
  agentUpdateProvider(id: number, json: string): Promise<string>
  agentDeleteProvider(id: number): Promise<void>
  agentSetDefaultProvider(id: number): Promise<void>
  apikeyList(): Promise<string>
  apikeyGet(id: number): Promise<string>
  apikeyCreate(json: string): Promise<string>
  apikeyUpdate(id: number, json: string): Promise<string>
  apikeyDelete(id: number): Promise<void>
  apikeyRevoke(id: number): Promise<void>
  authConnectLoginConnect(request: Array<number>): Promise<Array<number>>
  authConnectRegisterConnect(request: Array<number>): Promise<Array<number>>
  authConnectRefreshTokenConnect(request: Array<number>): Promise<Array<number>>
  authConnectVerifyEmailConnect(request: Array<number>): Promise<Array<number>>
  authConnectResendVerificationConnect(request: Array<number>): Promise<Array<number>>
  authConnectForgotPasswordConnect(request: Array<number>): Promise<Array<number>>
  authConnectResetPasswordConnect(request: Array<number>): Promise<Array<number>>
  authConnectOauthRedirectConnect(request: Array<number>): Promise<Array<number>>
  authConnectOauthCallbackConnect(request: Array<number>): Promise<Array<number>>
  authConnectLogoutConnect(request: Array<number>): Promise<Array<number>>
  autopilotControllersJson(): Promise<string>
  autopilotCurrentControllerJson(): Promise<string>
  autopilotGetControllerByPodKeyJson(podKey: string): Promise<string>
  autopilotGetIterationsJson(key: string): Promise<string>
  autopilotGetThinkingJson(key: string): Promise<string>
  autopilotGetThinkingHistoryJson(key: string): Promise<string>
  autopilotReplaceCachedControllers(reqBytes: Array<number>): Promise<void>
  autopilotSetCurrentControllerProto(reqBytes: Array<number>): Promise<void>
  autopilotInsertController(reqBytes: Array<number>): Promise<void>
  autopilotPatchController(reqBytes: Array<number>): Promise<void>
  autopilotRemoveControllerProto(reqBytes: Array<number>): Promise<void>
  autopilotReplaceCachedIterations(reqBytes: Array<number>): Promise<void>
  autopilotAppendIteration(reqBytes: Array<number>): Promise<void>
  autopilotUpdateThinkingProto(reqBytes: Array<number>): Promise<void>
  autopilotFetchControllers(): Promise<string>
  autopilotFetchController(key: string): Promise<string>
  autopilotCreateController(requestJson: string): Promise<string>
  autopilotPauseController(key: string): Promise<void>
  autopilotResumeController(key: string): Promise<void>
  autopilotStopController(key: string): Promise<void>
  autopilotApproveController(key: string, requestJson: string): Promise<void>
  autopilotTakeoverController(key: string): Promise<void>
  autopilotHandbackController(key: string): Promise<void>
  autopilotFetchIterations(key: string): Promise<string>
  billingGetOverview(): Promise<string>
  billingGetSubscription(): Promise<string>
  billingCreateSubscription(json: string): Promise<string>
  billingCancelSubscription(): Promise<string>
  billingUpdateSubscription(json: string): Promise<string>
  billingListPlans(): Promise<string>
  billingGetUsage(usageType?: string | undefined | null): Promise<string>
  billingCheckQuota(resource: string, amount?: number | undefined | null): Promise<string>
  billingCreateCheckout(json: string): Promise<string>
  billingGetCheckoutStatus(orderNo: string): Promise<string>
  billingRequestCancel(json: string): Promise<string>
  billingReactivate(): Promise<string>
  billingUpgrade(json: string): Promise<string>
  billingChangeCycle(json: string): Promise<string>
  billingUpdateAutoRenew(json: string): Promise<string>
  billingGetSeatUsage(): Promise<string>
  billingPurchaseSeats(json: string): Promise<string>
  billingListInvoices(limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  billingGetCustomerPortal(json: string): Promise<string>
  billingGetDeploymentInfo(): Promise<string>
  billingGetPublicPricing(): Promise<string>
  billingGetPublicDeploymentInfo(): Promise<string>
  bindingRequestBinding(json: string, podKey?: string | undefined | null): Promise<string>
  bindingAcceptBinding(json: string): Promise<string>
  bindingRejectBinding(json: string): Promise<void>
  bindingRequestScopes(bindingId: number, json: string): Promise<string>
  bindingApproveScopes(bindingId: number, json: string): Promise<string>
  bindingUnbind(json: string): Promise<void>
  bindingListBindings(status?: string | undefined | null): Promise<string>
  bindingGetPendingBindings(): Promise<string>
  bindingGetBoundPods(): Promise<string>
  bindingCheckBinding(targetPod: string): Promise<string>
  blockstoreApplyOps(reqJson: string): Promise<string>
  blockstoreListWorkspaces(): Promise<string>
  blockstoreEnsureDefaultWorkspace(): Promise<string>
  blockstoreLoadSubtree(workspaceId: string, rootId: string): Promise<void>
  blockstoreLoadTypeDefs(workspaceId: string): Promise<void>
  blockstoreCatchup(workspaceId: string): Promise<void>
  blockstoreSemanticSearch(workspaceId: string, reqJson: string): Promise<string>
  blockstoreApplyRemoteOp(opJson: string): Promise<void>
  blockstoreWorkspacesJson(): Promise<string>
  blockstoreGetBlockJson(id: string): Promise<string | null>
  blockstoreListChildrenJson(parentId: string): Promise<string>
  blockstoreListBacklinksJson(targetId: string): Promise<string>
  blockstoreTypeDefsJson(workspaceId: string): Promise<string>
  blockstoreLastOpId(workspaceId: string): Promise<number>
  blockstoreSetLastOpId(workspaceId: string, id: number): Promise<void>
  blockstoreBlocksJson(): Promise<string>
  blockstoreRefsJson(): Promise<string>
  blockstoreNestChildrenJson(): Promise<string>
  blockstoreBacklinksJson(): Promise<string>
  blockstoreLastOpIdsJson(): Promise<string>
  channelChannelsJson(): Promise<string>
  channelCurrentChannelJson(): Promise<string>
  channelGetChannelJson(id: number): Promise<string>
  channelFilterChannelsJson(query: string, includeArchived: boolean): Promise<string>
  channelGetMessagesJson(channelId: number): Promise<string>
  channelGetUnreadCount(channelId: number): Promise<number>
  channelTotalUnreadCount(): Promise<number>
  channelUnreadCountsJson(): Promise<string>
  channelGetMentionCount(channelId: number): Promise<number>
  channelTotalMentionCount(): Promise<number>
  channelMentionCountsJson(): Promise<string>
  channelSortedChannelIdsJson(mode: string, includeArchived: boolean): Promise<string>
  channelGetLastMessageJson(channelId: number): Promise<string>
  channelSetCurrentChannel(id?: number | undefined | null): Promise<void>
  channelSelectChannel(id?: number | undefined | null): Promise<string>
  channelUpdateChannelLocal(id: number, json: string): Promise<void>
  channelFetchChannels(includeArchived?: boolean | undefined | null): Promise<string>
  channelFetchChannel(id: number): Promise<string>
  channelCreateChannel(requestJson: string): Promise<string>
  channelUpdateChannel(id: number, requestJson: string): Promise<string>
  channelArchiveChannel(id: number): Promise<void>
  channelUnarchiveChannel(id: number): Promise<void>
  channelJoinChannel(channelId: number, podKey: string): Promise<string>
  channelLeaveChannel(channelId: number, podKey: string): Promise<string>
  channelFetchMessages(channelId: number, limit?: number | undefined | null, beforeId?: number | undefined | null): Promise<string>
  channelSendMessage(channelId: number, requestJson: string): Promise<string>
  channelEditMessage(channelId: number, messageId: number, content: string): Promise<string>
  channelDeleteMessage(channelId: number, messageId: number): Promise<void>
  channelFetchUnreadCounts(): Promise<string>
  channelMarkRead(channelId: number, messageId: number): Promise<void>
  channelMuteChannel(channelId: number, muted: boolean): Promise<void>
  channelGetChannelPods(id: number): Promise<string>
  channelChannelPodsJson(id: number): Promise<string>
  channelFetchChannelMembers(id: number): Promise<string>
  channelInviteChannelMembers(id: number, userIdsJson: string): Promise<void>
  channelRemoveChannelMember(id: number, userId: number): Promise<void>
  channelChannelMembersJson(id: number): Promise<string>
  channelSearchChannelMessages(id: number, q: string, limit?: number | undefined | null): Promise<string>
  channelSetCurrentUser(userJson: string): Promise<void>
  channelSetCurrentUserId(userId?: number | undefined | null): Promise<void>
  channelSetMessages(channelId: number, json: string, hasMore: boolean): Promise<void>
  channelPrependMessages(channelId: number, json: string, hasMore: boolean): Promise<void>
  channelAddMessage(channelId: number, json: string): Promise<void>
  channelOnNewMessage(json: string): Promise<boolean>
  channelUpdateMessageLocal(channelId: number, json: string): Promise<void>
  channelRemoveMessageLocal(channelId: number, messageId: number): Promise<void>
  channelSetUnreadCounts(json: string): Promise<void>
  channelIncrementUnread(channelId: number): Promise<void>
  channelClearChannelUnread(channelId: number): Promise<void>
  channelSetMentionCounts(json: string): Promise<void>
  channelIncrementMention(channelId: number): Promise<void>
  channelClearChannelMentions(channelId: number): Promise<void>
  channelSetLastMessage(channelId: number, json: string): Promise<void>
  extensionListSkillRegistries(): Promise<string>
  extensionCreateSkillRegistry(json: string): Promise<string>
  extensionSyncSkillRegistry(id: number): Promise<void>
  extensionToggleSkillRegistry(id: number, json: string): Promise<string>
  extensionDeleteSkillRegistry(id: number): Promise<void>
  extensionListSkillRegistryOverrides(): Promise<string>
  extensionListMarketSkills(query?: string | undefined | null, category?: string | undefined | null): Promise<string>
  extensionListMarketMcpServers(query?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  extensionListRepoSkills(repoId: number, scope?: string | undefined | null): Promise<string>
  extensionInstallSkillFromMarket(repoId: number, json: string): Promise<string>
  extensionInstallSkillFromGithub(repoId: number, json: string): Promise<string>
  extensionPresignSkillUploadConnect(request: Array<number>): Promise<Array<number>>
  extensionInstallSkillFromUploadedFileConnect(request: Array<number>): Promise<Array<number>>
  extensionUpdateSkill(repoId: number, installId: number, json: string): Promise<string>
  extensionUninstallSkill(repoId: number, installId: number): Promise<void>
  extensionListRepoMcpServers(repoId: number, scope?: string | undefined | null): Promise<string>
  extensionInstallMcpFromMarket(repoId: number, json: string): Promise<string>
  extensionInstallCustomMcpServer(repoId: number, json: string): Promise<string>
  extensionUpdateMcpServer(repoId: number, installId: number, json: string): Promise<string>
  extensionUninstallMcpServer(repoId: number, installId: number): Promise<void>
  filePresignUpload(json: string): Promise<string>
  fileUploadFile(fileData: Array<number>, filename: string, contentType: string): Promise<string>
  grantList(resourceType: string, resourceId: string): Promise<string>
  grantCreate(resourceType: string, resourceId: string, userId: number): Promise<string>
  grantRevoke(resourceType: string, resourceId: string, grantId: number): Promise<void>
  invitationListInvitationsConnect(request: Array<number>): Promise<Array<number>>
  invitationCreateInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationRevokeInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationResendInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationAcceptInvitationConnect(request: Array<number>): Promise<Array<number>>
  invitationListPendingInvitationsConnect(request: Array<number>): Promise<Array<number>>
  invitationGetInvitationByTokenConnect(request: Array<number>): Promise<Array<number>>
  localRunnerBinaryPath(): Promise<string>
  localRunnerHostTarget(): Promise<string | null>
  localRunnerIsInstalled(): Promise<boolean>
  localRunnerInstalledVersion(): Promise<string | null>
  localRunnerInstallBinary(releaseUrl: string, expectedSha256?: string | undefined | null): Promise<void>
  localRunnerIsRegistered(): Promise<boolean>
  localRunnerLocalNodeId(): Promise<string | null>
  localRunnerRegister(token: string): Promise<void>
  localRunnerServiceInstall(): Promise<void>
  localRunnerServiceUninstall(): Promise<void>
  localRunnerServiceStart(): Promise<void>
  localRunnerServiceStop(): Promise<void>
  localRunnerServiceStatus(): Promise<string>
  loopSvcLoopsJson(): Promise<string>
  loopSvcCurrentLoopJson(): Promise<string>
  loopSvcRunsJson(): Promise<string>
  loopSvcGetLoopBySlugJson(slug: string): Promise<string>
  loopSvcSetLoops(json: string): Promise<void>
  loopSvcSetCurrentLoop(json: string): Promise<void>
  loopSvcUpdateLoopLocal(slug: string, json: string): Promise<void>
  loopSvcAddRun(json: string): Promise<void>
  loopSvcSetRuns(json: string): Promise<void>
  loopSvcAppendRuns(json: string): Promise<void>
  loopSvcUpdateRunStatus(runId: number, status: string): Promise<void>
  loopSvcClearRuns(): Promise<void>
  loopSvcFetchLoops(status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  loopSvcFetchLoop(slug: string): Promise<string>
  loopSvcCreateLoop(requestJson: string): Promise<string>
  loopSvcUpdateLoop(slug: string, requestJson: string): Promise<string>
  loopSvcDeleteLoop(slug: string): Promise<void>
  loopSvcEnableLoop(slug: string): Promise<string>
  loopSvcDisableLoop(slug: string): Promise<string>
  loopSvcTriggerLoop(slug: string): Promise<string>
  loopSvcFetchRuns(slug: string, status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  loopSvcCancelRun(slug: string, runId: number): Promise<void>
  meshTopologyJson(): Promise<string>
  meshSelectedNode(): Promise<string>
  meshGetNodeJson(podKey: string): Promise<string>
  meshGetEdgesForNodeJson(podKey: string): Promise<string>
  meshGetChannelsForNodeJson(podKey: string): Promise<string>
  meshGetActiveNodesJson(): Promise<string>
  meshGetNodesByRunnerJson(runnerId: number): Promise<string>
  meshGetRunnerInfoJson(runnerId: number): Promise<string>
  meshSetTopology(json: string): Promise<void>
  meshClearTopology(): Promise<void>
  meshSelectNode(podKey?: string | undefined | null): Promise<void>
  meshFetchTopology(): Promise<string>
  messageSendMessage(json: string, podKey?: string | undefined | null): Promise<string>
  messageGetMessages(unreadOnly?: boolean | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  messageGetUnreadCount(): Promise<string>
  messageGetMessage(id: number): Promise<string>
  messageMarkRead(json: string): Promise<void>
  messageMarkAllRead(): Promise<void>
  messageGetConversation(correlationId: string, limit?: number | undefined | null): Promise<string>
  messageGetSentMessages(limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  messageGetDeadLetters(limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  messageReplayDeadLetter(entryId: number): Promise<void>
  notificationGetPreferences(): Promise<string>
  notificationSetPreference(json: string): Promise<string>
  orgList(): Promise<string>
  orgGet(slug: string): Promise<string>
  orgCreate(json: string): Promise<string>
  orgCreatePersonal(): Promise<string>
  orgUpdate(slug: string, json: string): Promise<string>
  orgDelete(slug: string): Promise<void>
  orgListMembers(slug: string): Promise<string>
  orgInviteMember(slug: string, json: string): Promise<string>
  orgRemoveMember(slug: string, userId: number): Promise<void>
  orgUpdateMemberRole(slug: string, userId: number, json: string): Promise<string>
  podPodsJson(): Promise<string>
  podCurrentPodJson(): Promise<string>
  podGetPodJson(podKey: string): Promise<string>
  podUpsertPod(podJson: string, timestamp?: number | undefined | null): Promise<void>
  podSetPods(podsJson: string): Promise<void>
  podSetCurrentPod(podJson: string): Promise<void>
  podUpdatePodStatus(podKey: string, status: string, agentStatus?: string | undefined | null, errorCode?: string | undefined | null, errorMessage?: string | undefined | null, timestamp?: number | undefined | null): Promise<void>
  podUpdatePodTitle(podKey: string, title: string, timestamp?: number | undefined | null): Promise<void>
  podUpdatePodAlias(podKey: string, alias: string): Promise<void>
  podUpdateAgentStatus(podKey: string, agentStatus: string): Promise<void>
  podRemovePod(podKey: string): Promise<void>
  podFetchPods(status?: string | undefined | null, runnerId?: number | undefined | null, createdById?: number | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  podFetchSidebarPods(filter: string, userId?: number | undefined | null): Promise<string>
  podLoadMorePods(filter: string, userId: number | undefined | null, offset: number): Promise<string>
  podFetchPod(podKey: string): Promise<string>
  podCreatePod(requestJson: string): Promise<string>
  podTerminatePod(podKey: string): Promise<void>
  podUpdatePodAliasApi(podKey: string, alias?: string | undefined | null): Promise<void>
  podGetPodConnection(podKey: string): Promise<string>
  repositoryList(): Promise<string>
  repositoryGet(id: number): Promise<string>
  repositoryCreate(json: string): Promise<string>
  repositoryUpdate(id: number, json: string): Promise<string>
  repositoryDelete(id: number): Promise<void>
  repositoryListBranches(id: number): Promise<string>
  repositorySyncBranches(id: number, json: string): Promise<string>
  repositoryRegisterWebhook(id: number): Promise<void>
  repositoryDeleteWebhook(id: number): Promise<void>
  repositoryGetWebhookStatus(id: number): Promise<string>
  repositoryGetWebhookSecret(id: number): Promise<string>
  repositoryListMergeRequests(id: number, branch?: string | undefined | null, mrState?: string | undefined | null): Promise<string>
  repositoryMarkWebhookConfigured(id: number): Promise<void>
  runnerRunnersJson(): Promise<string>
  runnerAvailableRunnersJson(): Promise<string>
  runnerCurrentRunnerJson(): Promise<string>
  runnerGetRunnerJson(id: number): Promise<string>
  runnerReplaceCachedRunners(reqBytes: Array<number>): Promise<void>
  runnerReplaceAvailableRunners(reqBytes: Array<number>): Promise<void>
  runnerSetCurrentRunnerProto(reqBytes: Array<number>): Promise<void>
  runnerPatchCachedRunner(reqBytes: Array<number>): Promise<void>
  runnerUpdateRunnerStatus(id: number, status: string): Promise<void>
  runnerRemoveCachedRunner(reqBytes: Array<number>): Promise<void>
  runnerFetchRunners(status?: string | undefined | null): Promise<string>
  runnerFetchAvailableRunners(): Promise<string>
  runnerFetchRunner(id: number): Promise<string>
  runnerUpdateRunner(id: number, requestJson: string): Promise<string>
  runnerDeleteRunner(id: number): Promise<void>
  runnerCreateToken(requestJson: string): Promise<string>
  runnerFetchTokens(): Promise<string>
  runnerDeleteToken(id: number): Promise<void>
  runnerListRunnerLogs(id: number): Promise<string>
  runnerRequestLogUpload(id: number): Promise<void>
  runnerUpgradeRunner(id: number, requestJson: string): Promise<string>
  runnerListRunnerPods(id: number, status?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): Promise<string>
  runnerQueryRunnerSandboxes(id: number, requestJson: string): Promise<string>
  runnerGetAuthStatus(authKey: string): Promise<string>
  runnerAuthorizeRunner(requestJson: string): Promise<string>
  supportTicketCreateTicket(title: string, category: string, content: string, priority: string | undefined | null, fileData: Array<Array<number>>, fileNames: Array<string>): Promise<string>
  supportTicketAddMessage(ticketId: number, content: string, fileData: Array<Array<number>>, fileNames: Array<string>): Promise<string>
  supportTicketListSupportTicketsConnect(request: Array<number>): Promise<Array<number>>
  supportTicketGetSupportTicketConnect(request: Array<number>): Promise<Array<number>>
  supportTicketGetAttachmentUrlConnect(request: Array<number>): Promise<Array<number>>
  ticketTicketsJson(): Promise<string>
  ticketGetTicketBySlugJson(slug: string): Promise<string>
  ticketCurrentTicketJson(): Promise<string>
  ticketBoardColumnsJson(): Promise<string>
  ticketLabelsJson(): Promise<string>
  ticketFilterTicketsJson(search: string, statusesJson: string, prioritiesJson: string, repositoryIdsJson: string): Promise<string>
  ticketSetTickets(json: string): Promise<void>
  ticketAddTicket(json: string): Promise<void>
  ticketUpdateTicketLocal(slug: string, json: string): Promise<void>
  ticketUpdateTicketStatusLocal(slug: string, status: string): Promise<void>
  ticketRemoveTicket(slug: string): Promise<void>
  ticketSetCurrentTicket(json: string): Promise<void>
  ticketSetBoardColumns(json: string): Promise<void>
  ticketAppendColumnTickets(status: string, json: string): Promise<void>
  ticketSetLabels(json: string): Promise<void>
  ticketAddLabel(json: string): Promise<void>
  ticketRemoveLabel(id: number): Promise<void>
  ticketListTicketsConnect(request: Array<number>): Promise<Array<number>>
  ticketGetTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketCreateTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketUpdateTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketDeleteTicketConnect(request: Array<number>): Promise<Array<number>>
  ticketUpdateTicketStatusConnect(request: Array<number>): Promise<Array<number>>
  ticketGetActiveTicketsConnect(request: Array<number>): Promise<Array<number>>
  ticketGetBoardConnect(request: Array<number>): Promise<Array<number>>
  ticketGetSubTicketsConnect(request: Array<number>): Promise<Array<number>>
  ticketAddAssigneeConnect(request: Array<number>): Promise<Array<number>>
  ticketRemoveAssigneeConnect(request: Array<number>): Promise<Array<number>>
  ticketListLabelsConnect(request: Array<number>): Promise<Array<number>>
  ticketCreateLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketUpdateLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketDeleteLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketAddLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketRemoveLabelConnect(request: Array<number>): Promise<Array<number>>
  ticketGetTicketPods(slug: string, activeOnly?: boolean | undefined | null): Promise<string>
  ticketTicketPodsJson(slug: string): Promise<string>
  ticketRelationsListRelationsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsCreateRelationConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsDeleteRelationConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListCommitsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsLinkCommitConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsUnlinkCommitConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListMergeRequestsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsListCommentsConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsCreateCommentConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsUpdateCommentConnect(request: Array<number>): Promise<Array<number>>
  ticketRelationsDeleteCommentConnect(request: Array<number>): Promise<Array<number>>
  tokenUsageGetDashboard(startTime?: string | undefined | null, endTime?: string | undefined | null, agentSlug?: string | undefined | null, userId?: number | undefined | null, model?: string | undefined | null, granularity?: string | undefined | null): Promise<string>
  userGetMeConnect(request: Array<number>): Promise<Array<number>>
  userUpdateMeConnect(request: Array<number>): Promise<Array<number>>
  userChangePasswordConnect(request: Array<number>): Promise<Array<number>>
  userListIdentitiesConnect(request: Array<number>): Promise<Array<number>>
  userDeleteIdentityConnect(request: Array<number>): Promise<Array<number>>
  userSearchUsersConnect(request: Array<number>): Promise<Array<number>>
  userCredentialListGitCredentials(): Promise<string>
  userCredentialCreateGitCredential(json: string): Promise<string>
  userCredentialGetGitCredential(id: number): Promise<string>
  userCredentialUpdateGitCredential(id: number, json: string): Promise<string>
  userCredentialDeleteGitCredential(id: number): Promise<void>
  userCredentialGetDefaultGitCredential(): Promise<string>
  userCredentialSetDefaultGitCredential(json: string): Promise<void>
  userCredentialClearDefaultGitCredential(): Promise<void>
  userCredentialListAgentCredentials(): Promise<string>
  userCredentialListAgentCredentialsForAgent(agentSlug: string): Promise<string>
  userCredentialCreateAgentCredential(agentSlug: string, json: string): Promise<string>
  userCredentialGetAgentCredential(id: number): Promise<string>
  userCredentialUpdateAgentCredential(id: number, json: string): Promise<string>
  userCredentialDeleteAgentCredential(id: number): Promise<void>
  userCredentialSetDefaultAgentCredential(id: number): Promise<void>
  userCredentialListRepoProviders(): Promise<string>
  userCredentialCreateRepoProvider(json: string): Promise<string>
  userCredentialGetRepoProvider(id: number): Promise<string>
  userCredentialUpdateRepoProvider(id: number, json: string): Promise<string>
  userCredentialDeleteRepoProvider(id: number): Promise<void>
  userCredentialSetDefaultRepoProvider(id: number): Promise<void>
  userCredentialTestRepoProvider(id: number): Promise<void>
  userCredentialListProviderRepositories(id: number, page?: number | undefined | null, perPage?: number | undefined | null, search?: string | undefined | null): Promise<string>
  ssoDiscoverConnect(request: Array<number>): Promise<Array<number>>
  ssoLdapAuthConnect(request: Array<number>): Promise<Array<number>>
  promocodeValidatePromoCodeConnect(request: Array<number>): Promise<Array<number>>
  promocodeRedeemPromoCodeConnect(request: Array<number>): Promise<Array<number>>
  promocodeGetRedemptionHistoryConnect(request: Array<number>): Promise<Array<number>>
}
