"""Next.js macro for AgentsMesh — ported from AIO with minimal tweaks.

For each `next_app()` call, produces four targets:
  :<name>               js_run_binary running `next build` (outputs `.next/`)
  :<name>_dev           devserver running `next dev`
  :<name>_start         devserver running `next start` against the build
  :<name>_start_binary  plain js_binary for the OCI image entrypoint

Used by clients/web and clients/web-admin. The Electron renderer bundle is
produced separately via build_defs/web/electron.bzl (which also calls
next_app under the hood).

Usage:
    load("@npm//clients/web:next/package_json.bzl", next_bin = "bin")
    load("//build_defs/web:next.bzl", "next_app")

    next_bin.next_binary(name = "next_js_binary")

    next_app(
        name = "next",
        srcs = [":src"],
        data = [
            "next.config.ts",
            "package.json",
            ":node_modules",
            "//:node_modules/agentsmesh-wasm",  # bazel-built wasm pkg
            ...
        ],
        next_js_binary = ":next_js_binary",
    )
"""

load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_run_binary", "js_run_devserver")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

# The generated entry script the OCI image invokes. It re-execs the
# Next.js CLI's `start` subcommand against the built `.next/` tree,
# reading the port from PORT (default 3000). Keeping the launcher in
# JS — rather than a wrapper sh — means `js_binary`'s node
# `patch_node_fs` machinery still applies.
_START_JS_CONTENTS = """#!/usr/bin/env node
// @generated by //build_defs/web:next.bzl — do not edit by hand.
// Boots `next start` with the .next/ directory shipped alongside.
const { spawnSync } = require("child_process");

const here = __dirname;
const nextBin = require.resolve("next/dist/bin/next", { paths: [here] });
const port = process.env.PORT || "3000";
const result = spawnSync(process.execPath, [nextBin, "start", "-p", port], {
  cwd: here,
  stdio: "inherit",
  env: process.env,
});
process.exit(result.status === null ? 1 : result.status);
"""

def next_app(
        name,
        srcs,
        data,
        next_js_binary,
        next_build_out = ".next",
        **kwargs):
    """Build / dev / start targets for a Next.js app.

    Args:
        name: Base target name (`:name` is the production build).
        srcs: Application source files (usually `ts_project` outputs).
        data: Runtime deps (node_modules, config files).
        next_js_binary: `js_binary` pointing at Next's CLI, typically
            produced by `next_bin.next_binary(name = "next_js_binary")`.
        next_build_out: Build artifact dir, defaults to `.next`.
        **kwargs: Tags + visibility forwarded to all targets.
    """
    tags = kwargs.pop("tags", [])

    js_run_binary(
        name = name,
        # Next.js 16 defaults to Turbopack for `next build`, but Turbopack
        # fails in the Bazel sandbox with "Symlink package.json is invalid,
        # it points out of the filesystem root" (it walks up past the
        # execroot looking for node_modules). Force the legacy webpack
        # pipeline for the OCI build; dev mode still uses Turbopack via
        # `next dev` below.
        args = [
            "build",
            "--webpack",
        ],
        chdir = native.package_name(),
        mnemonic = "NextJsBuild",
        out_dirs = [next_build_out],
        progress_message = "Building Next.js application",
        srcs = srcs + data,
        tags = tags,
        tool = next_js_binary,
        **kwargs
    )

    js_run_devserver(
        name = "{}_dev".format(name),
        # Force webpack — Turbopack walks symlink chains looking for
        # `next/package.json` and bombs out with "We couldn't find the
        # Next.js package" inside the Bazel sandbox (the aspect_rules_js
        # symlink tree exits the execroot prematurely). Same issue
        # `next build` already mitigates with --webpack above.
        args = [
            "dev",
            "--webpack",
        ],
        chdir = native.package_name(),
        data = srcs + data,
        grant_sandbox_write_permissions = True,
        tags = tags,
        tool = next_js_binary,
        **kwargs
    )

    js_run_devserver(
        name = "{}_start".format(name),
        args = ["start"],
        chdir = native.package_name(),
        data = data + [name],
        tags = tags,
        tool = next_js_binary,
        **kwargs
    )

    # Generate a tiny JS launcher so `js_binary` has a concrete entry
    # point. The script itself is deterministic — no stamping — and
    # lives in `bazel-bin/` under the package's own directory so
    # `js_image_layer` stages it next to `.next/` at /app/start.js.
    write_file(
        name = "{}_start_entry".format(name),
        out = "{}_start.js".format(name),
        content = _START_JS_CONTENTS.split("\n"),
        tags = tags + ["manual"],
    )

    js_binary(
        name = "{}_start_binary".format(name),
        chdir = native.package_name(),
        data = data + [name],
        entry_point = ":{}_start_entry".format(name),
        tags = tags,
        **kwargs
    )
